//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.V2.Models.iyibir_TMGD
{

    public partial class AuditDeterminationForm : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        Employee fOwner;
        [Association(@"AuditDeterminationFormReferencesEmployee")]
        public Employee Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<Employee>(nameof(Owner), ref fOwner, value); }
        }
        Customer fCustomer;
        [Association(@"AuditDeterminationFormReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        CustomerContact fCustomerContact;
        [Association(@"AuditDeterminationFormReferencesCustomerContact")]
        public CustomerContact CustomerContact
        {
            get { return fCustomerContact; }
            set { SetPropertyValue<CustomerContact>(nameof(CustomerContact), ref fCustomerContact, value); }
        }
        string fTaskName;
        public string TaskName
        {
            get { return fTaskName; }
            set { SetPropertyValue<string>(nameof(TaskName), ref fTaskName, value); }
        }
        string fReportNo;
        public string ReportNo
        {
            get { return fReportNo; }
            set { SetPropertyValue<string>(nameof(ReportNo), ref fReportNo, value); }
        }
        DateTime fReportDate;
        public DateTime ReportDate
        {
            get { return fReportDate; }
            set { SetPropertyValue<DateTime>(nameof(ReportDate), ref fReportDate, value); }
        }
        Position fPosition;
        [Association(@"AuditDeterminationFormReferencesPosition")]
        public Position Position
        {
            get { return fPosition; }
            set { SetPropertyValue<Position>(nameof(Position), ref fPosition, value); }
        }
        string fTMGDCertificate;
        public string TMGDCertificate
        {
            get { return fTMGDCertificate; }
            set { SetPropertyValue<string>(nameof(TMGDCertificate), ref fTMGDCertificate, value); }
        }
        string fReportSubject;
        public string ReportSubject
        {
            get { return fReportSubject; }
            set { SetPropertyValue<string>(nameof(ReportSubject), ref fReportSubject, value); }
        }
        string fCustomerAddress;
        public string CustomerAddress
        {
            get { return fCustomerAddress; }
            set { SetPropertyValue<string>(nameof(CustomerAddress), ref fCustomerAddress, value); }
        }
        DateTime fActivityDate;
        public DateTime ActivityDate
        {
            get { return fActivityDate; }
            set { SetPropertyValue<DateTime>(nameof(ActivityDate), ref fActivityDate, value); }
        }
        [Association(@"AuditDeterminationLegalStatuteReferencesAuditDeterminationForm")]
        public XPCollection<AuditDeterminationLegalStatute> AuditDeterminationLegalStatutes { get { return GetCollection<AuditDeterminationLegalStatute>(nameof(AuditDeterminationLegalStatutes)); } }
    }

}
