//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.V2.Models.iyibir_TMGD
{

    public partial class DrillFormControlList : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        DrillForm fDrillForm;
        [Association(@"DrillFormControlListReferencesDrillForm")]
        public DrillForm DrillForm
        {
            get { return fDrillForm; }
            set { SetPropertyValue<DrillForm>(nameof(DrillForm), ref fDrillForm, value); }
        }
        string fControlName;
        public string ControlName
        {
            get { return fControlName; }
            set { SetPropertyValue<string>(nameof(ControlName), ref fControlName, value); }
        }
        bool fIsControl;
        public bool IsControl
        {
            get { return fIsControl; }
            set { SetPropertyValue<bool>(nameof(IsControl), ref fIsControl, value); }
        }
        string fResult;
        [Size(450)]
        public string Result
        {
            get { return fResult; }
            set { SetPropertyValue<string>(nameof(Result), ref fResult, value); }
        }
    }

}
