//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.V2.Models.iyibir_TMGD
{

    public partial class DrillForm : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        Employee fOwner;
        [Association(@"DrillFormReferencesEmployee")]
        public Employee Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<Employee>(nameof(Owner), ref fOwner, value); }
        }
        Customer fCustomer;
        [Association(@"DrillFormReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        string fAddress;
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        DrillType fDrillType;
        [Association(@"DrillFormReferencesDrillType")]
        public DrillType DrillType
        {
            get { return fDrillType; }
            set { SetPropertyValue<DrillType>(nameof(DrillType), ref fDrillType, value); }
        }
        string fSubject;
        public string Subject
        {
            get { return fSubject; }
            set { SetPropertyValue<string>(nameof(Subject), ref fSubject, value); }
        }
        DateTime fDrillStartDate;
        public DateTime DrillStartDate
        {
            get { return fDrillStartDate; }
            set { SetPropertyValue<DateTime>(nameof(DrillStartDate), ref fDrillStartDate, value); }
        }
        double fDrillStartTime;
        public double DrillStartTime
        {
            get { return fDrillStartTime; }
            set { SetPropertyValue<double>(nameof(DrillStartTime), ref fDrillStartTime, value); }
        }
        string fDrillScenario;
        [Size(SizeAttribute.Unlimited)]
        public string DrillScenario
        {
            get { return fDrillScenario; }
            set { SetPropertyValue<string>(nameof(DrillScenario), ref fDrillScenario, value); }
        }
        [Association(@"DrillFormControlListReferencesDrillForm")]
        public XPCollection<DrillFormControlList> DrillFormControlLists { get { return GetCollection<DrillFormControlList>(nameof(DrillFormControlLists)); } }
    }

}
