//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.V2.Models.iyibir_TMGD
{

    public partial class Employee : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        int fColor;
        public int Color
        {
            get { return fColor; }
            set { SetPropertyValue<int>(nameof(Color), ref fColor, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fTCKN;
        [Size(11)]
        public string TCKN
        {
            get { return fTCKN; }
            set { SetPropertyValue<string>(nameof(TCKN), ref fTCKN, value); }
        }
        string fFirstName;
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
        }
        string fMiddleName;
        public string MiddleName
        {
            get { return fMiddleName; }
            set { SetPropertyValue<string>(nameof(MiddleName), ref fMiddleName, value); }
        }
        string fLastName;
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>(nameof(LastName), ref fLastName, value); }
        }
        string fEMail;
        public string EMail
        {
            get { return fEMail; }
            set { SetPropertyValue<string>(nameof(EMail), ref fEMail, value); }
        }
        string fWebAddress;
        public string WebAddress
        {
            get { return fWebAddress; }
            set { SetPropertyValue<string>(nameof(WebAddress), ref fWebAddress, value); }
        }
        string fTelephone;
        public string Telephone
        {
            get { return fTelephone; }
            set { SetPropertyValue<string>(nameof(Telephone), ref fTelephone, value); }
        }
        string fTelephone2;
        public string Telephone2
        {
            get { return fTelephone2; }
            set { SetPropertyValue<string>(nameof(Telephone2), ref fTelephone2, value); }
        }
        string fAddress;
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        string fClientMachineName;
        public string ClientMachineName
        {
            get { return fClientMachineName; }
            set { SetPropertyValue<string>(nameof(ClientMachineName), ref fClientMachineName, value); }
        }
        string fLogoUserName;
        public string LogoUserName
        {
            get { return fLogoUserName; }
            set { SetPropertyValue<string>(nameof(LogoUserName), ref fLogoUserName, value); }
        }
        Department fDepartment;
        [Association(@"EmployeeReferencesDepartment")]
        public Department Department
        {
            get { return fDepartment; }
            set { SetPropertyValue<Department>(nameof(Department), ref fDepartment, value); }
        }
        Position fPosition;
        [Association(@"EmployeeReferencesPosition")]
        public Position Position
        {
            get { return fPosition; }
            set { SetPropertyValue<Position>(nameof(Position), ref fPosition, value); }
        }
        MediaDataObject fImage;
        [Association(@"EmployeeReferencesMediaDataObject")]
        public MediaDataObject Image
        {
            get { return fImage; }
            set { SetPropertyValue<MediaDataObject>(nameof(Image), ref fImage, value); }
        }
        bool fIsManager;
        public bool IsManager
        {
            get { return fIsManager; }
            set { SetPropertyValue<bool>(nameof(IsManager), ref fIsManager, value); }
        }
        string fTMGDCertificate;
        public string TMGDCertificate
        {
            get { return fTMGDCertificate; }
            set { SetPropertyValue<string>(nameof(TMGDCertificate), ref fTMGDCertificate, value); }
        }
        FileData fTMGDCertificateFile;
        [Association(@"EmployeeReferencesFileData")]
        public FileData TMGDCertificateFile
        {
            get { return fTMGDCertificateFile; }
            set { SetPropertyValue<FileData>(nameof(TMGDCertificateFile), ref fTMGDCertificateFile, value); }
        }
        bool fIsActive;
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        string fUserName;
        public string UserName
        {
            get { return fUserName; }
            set { SetPropertyValue<string>(nameof(UserName), ref fUserName, value); }
        }
        bool fChangePasswordOnFirstLogon;
        public bool ChangePasswordOnFirstLogon
        {
            get { return fChangePasswordOnFirstLogon; }
            set { SetPropertyValue<bool>(nameof(ChangePasswordOnFirstLogon), ref fChangePasswordOnFirstLogon, value); }
        }
        string fStoredPassword;
        [Size(SizeAttribute.Unlimited)]
        public string StoredPassword
        {
            get { return fStoredPassword; }
            set { SetPropertyValue<string>(nameof(StoredPassword), ref fStoredPassword, value); }
        }
        string fCaption;
        public string Caption
        {
            get { return fCaption; }
            set { SetPropertyValue<string>(nameof(Caption), ref fCaption, value); }
        }
        int fEmployeeType;
        public int EmployeeType
        {
            get { return fEmployeeType; }
            set { SetPropertyValue<int>(nameof(EmployeeType), ref fEmployeeType, value); }
        }
        Customer fCustomer;
        [Association(@"EmployeeReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        [Association(@"ActivityReferencesEmployee")]
        public XPCollection<Activity> Activities { get { return GetCollection<Activity>(nameof(Activities)); } }
        [Association(@"ActivityReportReferencesEmployee")]
        public XPCollection<ActivityReport> ActivityReports { get { return GetCollection<ActivityReport>(nameof(ActivityReports)); } }
        [Association(@"AnnouncementReferencesEmployee")]
        public XPCollection<Announcement> Announcements { get { return GetCollection<Announcement>(nameof(Announcements)); } }
        [Association(@"AnnouncementUserReferencesEmployee")]
        public XPCollection<AnnouncementUser> AnnouncementUsers { get { return GetCollection<AnnouncementUser>(nameof(AnnouncementUsers)); } }
        [Association(@"AnnualWorkPlanReferencesEmployee")]
        public XPCollection<AnnualWorkPlan> AnnualWorkPlans { get { return GetCollection<AnnualWorkPlan>(nameof(AnnualWorkPlans)); } }
        [Association(@"AnnualWorkPlanSubjectReferencesEmployee")]
        public XPCollection<AnnualWorkPlanSubject> AnnualWorkPlanSubjects { get { return GetCollection<AnnualWorkPlanSubject>(nameof(AnnualWorkPlanSubjects)); } }
        [Association(@"AuditDeterminationFormReferencesEmployee")]
        public XPCollection<AuditDeterminationForm> AuditDeterminationForms { get { return GetCollection<AuditDeterminationForm>(nameof(AuditDeterminationForms)); } }
        [Association(@"ContractReferencesEmployee")]
        public XPCollection<Contract> Contracts { get { return GetCollection<Contract>(nameof(Contracts)); } }
        [Association(@"CustomDocumentReferencesEmployee")]
        public XPCollection<CustomDocument> CustomDocuments { get { return GetCollection<CustomDocument>(nameof(CustomDocuments)); } }
        [Association(@"CustomerReferencesEmployee")]
        public XPCollection<Customer> Customers { get { return GetCollection<Customer>(nameof(Customers)); } }
        [Association(@"CustomFileReferencesEmployee")]
        public XPCollection<CustomFile> CustomFiles { get { return GetCollection<CustomFile>(nameof(CustomFiles)); } }
        [Association(@"DepartmentReferencesEmployee")]
        public XPCollection<Department> Departments { get { return GetCollection<Department>(nameof(Departments)); } }
        [Association(@"DistributionOfTaskReferencesEmployee")]
        public XPCollection<DistributionOfTask> DistributionOfTasks { get { return GetCollection<DistributionOfTask>(nameof(DistributionOfTasks)); } }
        [Association(@"DrillFormReferencesEmployee")]
        public XPCollection<DrillForm> DrillForms { get { return GetCollection<DrillForm>(nameof(DrillForms)); } }
        [Association(@"EducationReferencesEmployee")]
        public XPCollection<Education> Educations { get { return GetCollection<Education>(nameof(Educations)); } }
        [Association(@"EmployeeDocumentReferencesEmployee")]
        public XPCollection<EmployeeDocument> EmployeeDocuments { get { return GetCollection<EmployeeDocument>(nameof(EmployeeDocuments)); } }
        [Association(@"EmployeeEmployees_AnnouncementAnnouncementsReferencesEmployee")]
        public XPCollection<EmployeeEmployees_AnnouncementAnnouncements> EmployeeEmployees_AnnouncementAnnouncementss { get { return GetCollection<EmployeeEmployees_AnnouncementAnnouncements>(nameof(EmployeeEmployees_AnnouncementAnnouncementss)); } }
        [Association(@"EmployeeRoleEmployeeRoles_EmployeeEmployeesReferencesEmployee")]
        public XPCollection<EmployeeRoleEmployeeRoles_EmployeeEmployees> EmployeeRoleEmployeeRoles_EmployeeEmployeess { get { return GetCollection<EmployeeRoleEmployeeRoles_EmployeeEmployees>(nameof(EmployeeRoleEmployeeRoles_EmployeeEmployeess)); } }
        [Association(@"iEventReferencesEmployee")]
        public XPCollection<iEvent> iEvents { get { return GetCollection<iEvent>(nameof(iEvents)); } }
        [Association(@"iEvent_EmployeesReferencesEmployee")]
        public XPCollection<iEvent_Employees> iEvent_Employeess { get { return GetCollection<iEvent_Employees>(nameof(iEvent_Employeess)); } }
        [Association(@"NoteReferencesEmployee")]
        public XPCollection<Note> Notes { get { return GetCollection<Note>(nameof(Notes)); } }
        [Association(@"QuoteReferencesEmployee")]
        public XPCollection<Quote> Quotes { get { return GetCollection<Quote>(nameof(Quotes)); } }
        [Association(@"ReportOnOccurrenceReferencesEmployee")]
        public XPCollection<ReportOnOccurrence> ReportOnOccurrences { get { return GetCollection<ReportOnOccurrence>(nameof(ReportOnOccurrences)); } }
        [Association(@"TransportDocumentReferencesEmployee")]
        public XPCollection<TransportDocument> TransportDocuments { get { return GetCollection<TransportDocument>(nameof(TransportDocuments)); } }
        [Association(@"VehicleControlDocumentReferencesEmployee")]
        public XPCollection<VehicleControlDocument> VehicleControlDocuments { get { return GetCollection<VehicleControlDocument>(nameof(VehicleControlDocuments)); } }
        [Association(@"VehicleDocumentReferencesEmployee")]
        public XPCollection<VehicleDocument> VehicleDocuments { get { return GetCollection<VehicleDocument>(nameof(VehicleDocuments)); } }
        [Association(@"VehicleDriverDocumentReferencesEmployee")]
        public XPCollection<VehicleDriverDocument> VehicleDriverDocuments { get { return GetCollection<VehicleDriverDocument>(nameof(VehicleDriverDocuments)); } }
    }

}
