//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.V2.Models.iyibir_TMGD
{

    public partial class HazardousGoodsSpecialProvisionForCarriageOperationSpecialProvisionForCarriageOperation_HazardousGoodsHazardousGoods : XPBaseObject
    {
        HazardousGoods fHazardousGoods;
        [Indexed(@"SpecialProvisionForCarriageOperation", Name = @"iHazardousGoodsSpecialProvisionForCarriageOperation_HazardousGoodsSpecialProvisionForCarriageOperationSpecialProvisionF_76BA9C06", Unique = true)]
        [Association(@"HazardousGoodsSpecialProvisionForCarriageOperationSpecialProvisionForCarriageOperation_HazardousGoodsHazardousGoodsReferencesHazardousGoods")]
        public HazardousGoods HazardousGoods
        {
            get { return fHazardousGoods; }
            set { SetPropertyValue<HazardousGoods>(nameof(HazardousGoods), ref fHazardousGoods, value); }
        }
        HazardousGoodsSpecialProvisionForCarriageOperation fSpecialProvisionForCarriageOperation;
        [Association(@"HazardousGoodsSpecialProvisionForCarriageOperationSpecialProvisionForCarriageOperation_HazardousGoodsHazardousGoodsReferencesHazardousGoodsSpecialProvisionForCarriageOperation")]
        public HazardousGoodsSpecialProvisionForCarriageOperation SpecialProvisionForCarriageOperation
        {
            get { return fSpecialProvisionForCarriageOperation; }
            set { SetPropertyValue<HazardousGoodsSpecialProvisionForCarriageOperation>(nameof(SpecialProvisionForCarriageOperation), ref fSpecialProvisionForCarriageOperation, value); }
        }
        Guid fOID;
        [Key(true)]
        public Guid OID
        {
            get { return fOID; }
            set { SetPropertyValue<Guid>(nameof(OID), ref fOID, value); }
        }
    }

}
