//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.V2.Models.iyibir_TMGD
{

    public partial class HazardousGoodsMixedPackingProvisionMixedPackingProvisions_HazardousGoodsHazardousGoods : XPBaseObject
    {
        HazardousGoods fHazardousGoods;
        [Indexed(@"MixedPackingProvisions", Name = @"iHazardousGoodsMixedPackingProvisions_HazardousGoodsMixedPackingProvisionMixedPackingProvisions_HazardousGoodsHazardousGoods", Unique = true)]
        [Association(@"HazardousGoodsMixedPackingProvisionMixedPackingProvisions_HazardousGoodsHazardousGoodsReferencesHazardousGoods")]
        public HazardousGoods HazardousGoods
        {
            get { return fHazardousGoods; }
            set { SetPropertyValue<HazardousGoods>(nameof(HazardousGoods), ref fHazardousGoods, value); }
        }
        HazardousGoodsMixedPackingProvision fMixedPackingProvisions;
        [Association(@"HazardousGoodsMixedPackingProvisionMixedPackingProvisions_HazardousGoodsHazardousGoodsReferencesHazardousGoodsMixedPackingProvision")]
        public HazardousGoodsMixedPackingProvision MixedPackingProvisions
        {
            get { return fMixedPackingProvisions; }
            set { SetPropertyValue<HazardousGoodsMixedPackingProvision>(nameof(MixedPackingProvisions), ref fMixedPackingProvisions, value); }
        }
        Guid fOID;
        [Key(true)]
        public Guid OID
        {
            get { return fOID; }
            set { SetPropertyValue<Guid>(nameof(OID), ref fOID, value); }
        }
    }

}
