//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.V2.Models.iyibir_TMGD
{

    public partial class HazardousGoodsLimitedQuantityLimitedQuantities_HazardousGoodsHazardousGoods : XPBaseObject
    {
        HazardousGoods fHazardousGoods;
        [Indexed(@"LimitedQuantities", Name = @"iHazardousGoodsLimitedQuantities_HazardousGoodsLimitedQuantityLimitedQuantities_HazardousGoodsHazardousGoods", Unique = true)]
        [Association(@"HazardousGoodsLimitedQuantityLimitedQuantities_HazardousGoodsHazardousGoodsReferencesHazardousGoods")]
        public HazardousGoods HazardousGoods
        {
            get { return fHazardousGoods; }
            set { SetPropertyValue<HazardousGoods>(nameof(HazardousGoods), ref fHazardousGoods, value); }
        }
        HazardousGoodsLimitedQuantity fLimitedQuantities;
        [Association(@"HazardousGoodsLimitedQuantityLimitedQuantities_HazardousGoodsHazardousGoodsReferencesHazardousGoodsLimitedQuantity")]
        public HazardousGoodsLimitedQuantity LimitedQuantities
        {
            get { return fLimitedQuantities; }
            set { SetPropertyValue<HazardousGoodsLimitedQuantity>(nameof(LimitedQuantities), ref fLimitedQuantities, value); }
        }
        Guid fOID;
        [Key(true)]
        public Guid OID
        {
            get { return fOID; }
            set { SetPropertyValue<Guid>(nameof(OID), ref fOID, value); }
        }
    }

}
