//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.V2.Models.iyibir_TMGD
{

    public partial class MediaDataObject : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        byte[] fMediaData;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] MediaData
        {
            get { return fMediaData; }
            set { SetPropertyValue<byte[]>(nameof(MediaData), ref fMediaData, value); }
        }
        string fMediaDataKey;
        public string MediaDataKey
        {
            get { return fMediaDataKey; }
            set { SetPropertyValue<string>(nameof(MediaDataKey), ref fMediaDataKey, value); }
        }
        [Association(@"EmployeeReferencesMediaDataObject")]
        public XPCollection<Employee> Employees { get { return GetCollection<Employee>(nameof(Employees)); } }
    }

}
