//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.V2.Models.iyibir_TMGD
{

    public partial class PackagingTypes : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        [Association(@"CustomerInventoryReferencesPackagingTypes")]
        public XPCollection<CustomerInventory> CustomerInventories { get { return GetCollection<CustomerInventory>(nameof(CustomerInventories)); } }
        [Association(@"CustomerWasteInventoryReferencesPackagingTypes")]
        public XPCollection<CustomerWasteInventory> CustomerWasteInventories { get { return GetCollection<CustomerWasteInventory>(nameof(CustomerWasteInventories)); } }
        [Association(@"TransportDocumentOtherTransactionReferencesPackagingTypes")]
        public XPCollection<TransportDocumentOtherTransaction> TransportDocumentOtherTransactions { get { return GetCollection<TransportDocumentOtherTransaction>(nameof(TransportDocumentOtherTransactions)); } }
        [Association(@"TransportDocumentTransactionReferencesPackagingTypes")]
        public XPCollection<TransportDocumentTransaction> TransportDocumentTransactions { get { return GetCollection<TransportDocumentTransaction>(nameof(TransportDocumentTransactions)); } }
    }

}
