//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.V2.Models.iyibir_TMGD
{

    public partial class PackingGroup : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        HazardousGoods fHazardousGoods;
        [Association(@"PackingGroupReferencesHazardousGoods")]
        public HazardousGoods HazardousGoods
        {
            get { return fHazardousGoods; }
            set { SetPropertyValue<HazardousGoods>(nameof(HazardousGoods), ref fHazardousGoods, value); }
        }
        [Association(@"CustomerInventoryReferencesPackingGroup")]
        public XPCollection<CustomerInventory> CustomerInventories { get { return GetCollection<CustomerInventory>(nameof(CustomerInventories)); } }
        [Association(@"CustomerWasteInventoryReferencesPackingGroup")]
        public XPCollection<CustomerWasteInventory> CustomerWasteInventories { get { return GetCollection<CustomerWasteInventory>(nameof(CustomerWasteInventories)); } }
        [Association(@"DangerousGoodInvolvedReferencesPackingGroup")]
        public XPCollection<DangerousGoodInvolved> DangerousGoodInvolveds { get { return GetCollection<DangerousGoodInvolved>(nameof(DangerousGoodInvolveds)); } }
        [Association(@"HazardousGoodsReferencesPackingGroup")]
        public XPCollection<HazardousGoods> HazardousGoodsCollection { get { return GetCollection<HazardousGoods>(nameof(HazardousGoodsCollection)); } }
        [Association(@"PackingGroupPackingGroups_HazardousGoodsHazardousGoodsReferencesPackingGroup")]
        public XPCollection<PackingGroupPackingGroups_HazardousGoodsHazardousGoods> PackingGroupPackingGroups_HazardousGoodsHazardousGoodss { get { return GetCollection<PackingGroupPackingGroups_HazardousGoodsHazardousGoods>(nameof(PackingGroupPackingGroups_HazardousGoodsHazardousGoodss)); } }
        [Association(@"TransportDocumentOtherTransactionReferencesPackingGroup")]
        public XPCollection<TransportDocumentOtherTransaction> TransportDocumentOtherTransactions { get { return GetCollection<TransportDocumentOtherTransaction>(nameof(TransportDocumentOtherTransactions)); } }
        [Association(@"TransportDocumentTransactionReferencesPackingGroup")]
        public XPCollection<TransportDocumentTransaction> TransportDocumentTransactions { get { return GetCollection<TransportDocumentTransaction>(nameof(TransportDocumentTransactions)); } }
    }

}
