//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.V2.Models.iyibir_TMGD
{

    public partial class PermissionPolicyTypePermissionsObject : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        PermissionPolicyRole fRole;
        [Association(@"PermissionPolicyTypePermissionsObjectReferencesPermissionPolicyRole")]
        public PermissionPolicyRole Role
        {
            get { return fRole; }
            set { SetPropertyValue<PermissionPolicyRole>(nameof(Role), ref fRole, value); }
        }
        string fTargetType;
        [Size(SizeAttribute.Unlimited)]
        public string TargetType
        {
            get { return fTargetType; }
            set { SetPropertyValue<string>(nameof(TargetType), ref fTargetType, value); }
        }
        int fReadState;
        public int ReadState
        {
            get { return fReadState; }
            set { SetPropertyValue<int>(nameof(ReadState), ref fReadState, value); }
        }
        int fWriteState;
        public int WriteState
        {
            get { return fWriteState; }
            set { SetPropertyValue<int>(nameof(WriteState), ref fWriteState, value); }
        }
        int fCreateState;
        public int CreateState
        {
            get { return fCreateState; }
            set { SetPropertyValue<int>(nameof(CreateState), ref fCreateState, value); }
        }
        int fDeleteState;
        public int DeleteState
        {
            get { return fDeleteState; }
            set { SetPropertyValue<int>(nameof(DeleteState), ref fDeleteState, value); }
        }
        int fNavigateState;
        public int NavigateState
        {
            get { return fNavigateState; }
            set { SetPropertyValue<int>(nameof(NavigateState), ref fNavigateState, value); }
        }
        [Association(@"PermissionPolicyMemberPermissionsObjectReferencesPermissionPolicyTypePermissionsObject")]
        public XPCollection<PermissionPolicyMemberPermissionsObject> PermissionPolicyMemberPermissionsObjects { get { return GetCollection<PermissionPolicyMemberPermissionsObject>(nameof(PermissionPolicyMemberPermissionsObjects)); } }
        [Association(@"PermissionPolicyObjectPermissionsObjectReferencesPermissionPolicyTypePermissionsObject")]
        public XPCollection<PermissionPolicyObjectPermissionsObject> PermissionPolicyObjectPermissionsObjects { get { return GetCollection<PermissionPolicyObjectPermissionsObject>(nameof(PermissionPolicyObjectPermissionsObjects)); } }
    }

}
