//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.V2.Models.iyibir_TMGD
{

    public partial class Sector : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        [Association(@"ActivityReferencesSector")]
        public XPCollection<Activity> Activities { get { return GetCollection<Activity>(nameof(Activities)); } }
        [Association(@"CustomerReferencesSector")]
        public XPCollection<Customer> Customers { get { return GetCollection<Customer>(nameof(Customers)); } }
        [Association(@"DistributionOfTaskReferencesSector")]
        public XPCollection<DistributionOfTask> DistributionOfTasks { get { return GetCollection<DistributionOfTask>(nameof(DistributionOfTasks)); } }
    }

}
