//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.V2.Models.iyibir_TMGD
{

    public partial class TransportDocument : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        DateTime fCreatedDate;
        public DateTime CreatedDate
        {
            get { return fCreatedDate; }
            set { SetPropertyValue<DateTime>(nameof(CreatedDate), ref fCreatedDate, value); }
        }
        double fCreatedTime;
        public double CreatedTime
        {
            get { return fCreatedTime; }
            set { SetPropertyValue<double>(nameof(CreatedTime), ref fCreatedTime, value); }
        }
        Employee fOwner;
        [Association(@"TransportDocumentReferencesEmployee")]
        public Employee Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<Employee>(nameof(Owner), ref fOwner, value); }
        }
        Customer fConsigner;
        [Association(@"TransportDocumentReferencesCustomer")]
        public Customer Consigner
        {
            get { return fConsigner; }
            set { SetPropertyValue<Customer>(nameof(Consigner), ref fConsigner, value); }
        }
        string fConsignerTaxOffice;
        public string ConsignerTaxOffice
        {
            get { return fConsignerTaxOffice; }
            set { SetPropertyValue<string>(nameof(ConsignerTaxOffice), ref fConsignerTaxOffice, value); }
        }
        string fConsignerTaxNumber;
        public string ConsignerTaxNumber
        {
            get { return fConsignerTaxNumber; }
            set { SetPropertyValue<string>(nameof(ConsignerTaxNumber), ref fConsignerTaxNumber, value); }
        }
        string fConsignerAddress;
        public string ConsignerAddress
        {
            get { return fConsignerAddress; }
            set { SetPropertyValue<string>(nameof(ConsignerAddress), ref fConsignerAddress, value); }
        }
        Consignee fConsignee;
        [Association(@"TransportDocumentReferencesConsignee")]
        public Consignee Consignee
        {
            get { return fConsignee; }
            set { SetPropertyValue<Consignee>(nameof(Consignee), ref fConsignee, value); }
        }
        string fConsigneeTaxOffice;
        public string ConsigneeTaxOffice
        {
            get { return fConsigneeTaxOffice; }
            set { SetPropertyValue<string>(nameof(ConsigneeTaxOffice), ref fConsigneeTaxOffice, value); }
        }
        string fConsigneeTaxNumber;
        public string ConsigneeTaxNumber
        {
            get { return fConsigneeTaxNumber; }
            set { SetPropertyValue<string>(nameof(ConsigneeTaxNumber), ref fConsigneeTaxNumber, value); }
        }
        string fConsigneeAddress;
        public string ConsigneeAddress
        {
            get { return fConsigneeAddress; }
            set { SetPropertyValue<string>(nameof(ConsigneeAddress), ref fConsigneeAddress, value); }
        }
        Vehicle fVehicle;
        [Association(@"TransportDocumentReferencesVehicle")]
        public Vehicle Vehicle
        {
            get { return fVehicle; }
            set { SetPropertyValue<Vehicle>(nameof(Vehicle), ref fVehicle, value); }
        }
        VehicleDriver fDriver;
        [Association(@"TransportDocumentReferencesVehicleDriver")]
        public VehicleDriver Driver
        {
            get { return fDriver; }
            set { SetPropertyValue<VehicleDriver>(nameof(Driver), ref fDriver, value); }
        }
        string fTransportCategory;
        public string TransportCategory
        {
            get { return fTransportCategory; }
            set { SetPropertyValue<string>(nameof(TransportCategory), ref fTransportCategory, value); }
        }
        double fScoreQuantity;
        public double ScoreQuantity
        {
            get { return fScoreQuantity; }
            set { SetPropertyValue<double>(nameof(ScoreQuantity), ref fScoreQuantity, value); }
        }
        string fTunnelCode;
        public string TunnelCode
        {
            get { return fTunnelCode; }
            set { SetPropertyValue<string>(nameof(TunnelCode), ref fTunnelCode, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        int fTransportDocumentType;
        public int TransportDocumentType
        {
            get { return fTransportDocumentType; }
            set { SetPropertyValue<int>(nameof(TransportDocumentType), ref fTransportDocumentType, value); }
        }
        bool fIsSpecial;
        public bool IsSpecial
        {
            get { return fIsSpecial; }
            set { SetPropertyValue<bool>(nameof(IsSpecial), ref fIsSpecial, value); }
        }
        Consignee fShipper;
        [Association(@"TransportDocumentReferencesConsignee1")]
        public Consignee Shipper
        {
            get { return fShipper; }
            set { SetPropertyValue<Consignee>(nameof(Shipper), ref fShipper, value); }
        }
        string fSpecialShipper;
        public string SpecialShipper
        {
            get { return fSpecialShipper; }
            set { SetPropertyValue<string>(nameof(SpecialShipper), ref fSpecialShipper, value); }
        }
        [Association(@"TransportDocumentOtherTransactionReferencesTransportDocument")]
        public XPCollection<TransportDocumentOtherTransaction> TransportDocumentOtherTransactions { get { return GetCollection<TransportDocumentOtherTransaction>(nameof(TransportDocumentOtherTransactions)); } }
        [Association(@"TransportDocumentTransactionReferencesTransportDocument")]
        public XPCollection<TransportDocumentTransaction> TransportDocumentTransactions { get { return GetCollection<TransportDocumentTransaction>(nameof(TransportDocumentTransactions)); } }
    }

}
