//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class ActivitySubjectDesc : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        ActivitySubject fActivitySubject;
        [Association(@"ActivitySubjectDescReferencesActivitySubject")]
        public ActivitySubject ActivitySubject
        {
            get { return fActivitySubject; }
            set { SetPropertyValue<ActivitySubject>(nameof(ActivitySubject), ref fActivitySubject, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        [Association(@"ActivityLineReferencesActivitySubjectDesc")]
        public XPCollection<ActivityLine> ActivityLines { get { return GetCollection<ActivityLine>(nameof(ActivityLines)); } }
    }

}
