//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class Analysis : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fDimensionPropertiesString;
        [Size(SizeAttribute.Unlimited)]
        public string DimensionPropertiesString
        {
            get { return fDimensionPropertiesString; }
            set { SetPropertyValue<string>(nameof(DimensionPropertiesString), ref fDimensionPropertiesString, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fCriteria;
        [Size(SizeAttribute.Unlimited)]
        public string Criteria
        {
            get { return fCriteria; }
            set { SetPropertyValue<string>(nameof(Criteria), ref fCriteria, value); }
        }
        string fObjectTypeName;
        [Size(SizeAttribute.Unlimited)]
        public string ObjectTypeName
        {
            get { return fObjectTypeName; }
            set { SetPropertyValue<string>(nameof(ObjectTypeName), ref fObjectTypeName, value); }
        }
        byte[] fChartSettingsContent;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] ChartSettingsContent
        {
            get { return fChartSettingsContent; }
            set { SetPropertyValue<byte[]>(nameof(ChartSettingsContent), ref fChartSettingsContent, value); }
        }
        byte[] fPivotGridSettingsContent;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] PivotGridSettingsContent
        {
            get { return fPivotGridSettingsContent; }
            set { SetPropertyValue<byte[]>(nameof(PivotGridSettingsContent), ref fPivotGridSettingsContent, value); }
        }
    }

}
