//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class AnnouncementUser : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        Announcement fAnnouncement;
        [Association(@"AnnouncementUserReferencesAnnouncement")]
        public Announcement Announcement
        {
            get { return fAnnouncement; }
            set { SetPropertyValue<Announcement>(nameof(Announcement), ref fAnnouncement, value); }
        }
        Employee fEmployee;
        [Association(@"AnnouncementUserReferencesEmployee")]
        public Employee Employee
        {
            get { return fEmployee; }
            set { SetPropertyValue<Employee>(nameof(Employee), ref fEmployee, value); }
        }
        bool fIsRead;
        public bool IsRead
        {
            get { return fIsRead; }
            set { SetPropertyValue<bool>(nameof(IsRead), ref fIsRead, value); }
        }
        DateTime fReadDate;
        public DateTime ReadDate
        {
            get { return fReadDate; }
            set { SetPropertyValue<DateTime>(nameof(ReadDate), ref fReadDate, value); }
        }
    }

}
