//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class AnnualWorkPlanSubject : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        AnnualWorkPlan fAnnualWorkPlan;
        [Association(@"AnnualWorkPlanSubjectReferencesAnnualWorkPlan")]
        public AnnualWorkPlan AnnualWorkPlan
        {
            get { return fAnnualWorkPlan; }
            set { SetPropertyValue<AnnualWorkPlan>(nameof(AnnualWorkPlan), ref fAnnualWorkPlan, value); }
        }
        string fSubject;
        public string Subject
        {
            get { return fSubject; }
            set { SetPropertyValue<string>(nameof(Subject), ref fSubject, value); }
        }
        int fSubjectStatus;
        public int SubjectStatus
        {
            get { return fSubjectStatus; }
            set { SetPropertyValue<int>(nameof(SubjectStatus), ref fSubjectStatus, value); }
        }
        Employee fAuthorizedPerson;
        [Association(@"AnnualWorkPlanSubjectReferencesEmployee")]
        public Employee AuthorizedPerson
        {
            get { return fAuthorizedPerson; }
            set { SetPropertyValue<Employee>(nameof(AuthorizedPerson), ref fAuthorizedPerson, value); }
        }
        DateTime fDueDate;
        public DateTime DueDate
        {
            get { return fDueDate; }
            set { SetPropertyValue<DateTime>(nameof(DueDate), ref fDueDate, value); }
        }
        [Association(@"ActivityLineReferencesAnnualWorkPlanSubject")]
        public XPCollection<ActivityLine> ActivityLines { get { return GetCollection<ActivityLine>(nameof(ActivityLines)); } }
        [Association(@"AnnualWorkPlanSubjectTransactionReferencesAnnualWorkPlanSubject")]
        public XPCollection<AnnualWorkPlanSubjectTransaction> AnnualWorkPlanSubjectTransactions { get { return GetCollection<AnnualWorkPlanSubjectTransaction>(nameof(AnnualWorkPlanSubjectTransactions)); } }
    }

}
