//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class AuditDeterminationLegalStatuteTransaction : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        AuditDeterminationLegalStatute fAuditDeterminationLegalStatute;
        [Association(@"AuditDeterminationLegalStatuteTransactionReferencesAuditDeterminationLegalStatute")]
        public AuditDeterminationLegalStatute AuditDeterminationLegalStatute
        {
            get { return fAuditDeterminationLegalStatute; }
            set { SetPropertyValue<AuditDeterminationLegalStatute>(nameof(AuditDeterminationLegalStatute), ref fAuditDeterminationLegalStatute, value); }
        }
        string fAuditDetermination;
        [Size(SizeAttribute.Unlimited)]
        public string AuditDetermination
        {
            get { return fAuditDetermination; }
            set { SetPropertyValue<string>(nameof(AuditDetermination), ref fAuditDetermination, value); }
        }
        string fResult;
        [Size(SizeAttribute.Unlimited)]
        public string Result
        {
            get { return fResult; }
            set { SetPropertyValue<string>(nameof(Result), ref fResult, value); }
        }
        FileData fFileData;
        [Association(@"AuditDeterminationLegalStatuteTransactionReferencesFileData")]
        public FileData FileData
        {
            get { return fFileData; }
            set { SetPropertyValue<FileData>(nameof(FileData), ref fFileData, value); }
        }
        byte[] fImage;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Image
        {
            get { return fImage; }
            set { SetPropertyValue<byte[]>(nameof(Image), ref fImage, value); }
        }
        byte[] fImage1;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Image1
        {
            get { return fImage1; }
            set { SetPropertyValue<byte[]>(nameof(Image1), ref fImage1, value); }
        }
        byte[] fImage2;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Image2
        {
            get { return fImage2; }
            set { SetPropertyValue<byte[]>(nameof(Image2), ref fImage2, value); }
        }
    }

}
