//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class City : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        Country fCountry;
        [Association(@"CityReferencesCountry")]
        public Country Country
        {
            get { return fCountry; }
            set { SetPropertyValue<Country>(nameof(Country), ref fCountry, value); }
        }
        double fLongitude;
        public double Longitude
        {
            get { return fLongitude; }
            set { SetPropertyValue<double>(nameof(Longitude), ref fLongitude, value); }
        }
        double fLatitude;
        public double Latitude
        {
            get { return fLatitude; }
            set { SetPropertyValue<double>(nameof(Latitude), ref fLatitude, value); }
        }
        [Association(@"CompanyReferencesCity")]
        public XPCollection<Company> Companies { get { return GetCollection<Company>(nameof(Companies)); } }
        [Association(@"ConsigneeReferencesCity")]
        public XPCollection<Consignee> Consignees { get { return GetCollection<Consignee>(nameof(Consignees)); } }
        [Association(@"CountyReferencesCity")]
        public XPCollection<County> Counties { get { return GetCollection<County>(nameof(Counties)); } }
        [Association(@"CustomerReferencesCity")]
        public XPCollection<Customer> Customers { get { return GetCollection<Customer>(nameof(Customers)); } }
        [Association(@"CustomerContactReferencesCity")]
        public XPCollection<CustomerContact> CustomerContacts { get { return GetCollection<CustomerContact>(nameof(CustomerContacts)); } }
        [Association(@"LeadReferencesCity")]
        public XPCollection<Lead> Leads { get { return GetCollection<Lead>(nameof(Leads)); } }
    }

}
