//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class CustomerInventory : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        Customer fCustomer;
        [Association(@"CustomerInventoryReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        HazardousGoods fHazardousGoods;
        [Association(@"CustomerInventoryReferencesHazardousGoods")]
        public HazardousGoods HazardousGoods
        {
            get { return fHazardousGoods; }
            set { SetPropertyValue<HazardousGoods>(nameof(HazardousGoods), ref fHazardousGoods, value); }
        }
        bool fIsWaste;
        public bool IsWaste
        {
            get { return fIsWaste; }
            set { SetPropertyValue<bool>(nameof(IsWaste), ref fIsWaste, value); }
        }
        string fInventoryCode;
        public string InventoryCode
        {
            get { return fInventoryCode; }
            set { SetPropertyValue<string>(nameof(InventoryCode), ref fInventoryCode, value); }
        }
        string fInventoryName;
        public string InventoryName
        {
            get { return fInventoryName; }
            set { SetPropertyValue<string>(nameof(InventoryName), ref fInventoryName, value); }
        }
        byte[] fInventoryImage;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] InventoryImage
        {
            get { return fInventoryImage; }
            set { SetPropertyValue<byte[]>(nameof(InventoryImage), ref fInventoryImage, value); }
        }
        FactoryDepartment fFactoryDepartment;
        [Association(@"CustomerInventoryReferencesFactoryDepartment")]
        public FactoryDepartment FactoryDepartment
        {
            get { return fFactoryDepartment; }
            set { SetPropertyValue<FactoryDepartment>(nameof(FactoryDepartment), ref fFactoryDepartment, value); }
        }
        string fSupplier;
        public string Supplier
        {
            get { return fSupplier; }
            set { SetPropertyValue<string>(nameof(Supplier), ref fSupplier, value); }
        }
        double fPackagingQuantity;
        public double PackagingQuantity
        {
            get { return fPackagingQuantity; }
            set { SetPropertyValue<double>(nameof(PackagingQuantity), ref fPackagingQuantity, value); }
        }
        FileData fFileData;
        [Association(@"CustomerInventoryReferencesFileData")]
        public FileData FileData
        {
            get { return fFileData; }
            set { SetPropertyValue<FileData>(nameof(FileData), ref fFileData, value); }
        }
        double fLastYearIntake;
        public double LastYearIntake
        {
            get { return fLastYearIntake; }
            set { SetPropertyValue<double>(nameof(LastYearIntake), ref fLastYearIntake, value); }
        }
        int fMSDSStatus;
        public int MSDSStatus
        {
            get { return fMSDSStatus; }
            set { SetPropertyValue<int>(nameof(MSDSStatus), ref fMSDSStatus, value); }
        }
        bool fConsignor;
        public bool Consignor
        {
            get { return fConsignor; }
            set { SetPropertyValue<bool>(nameof(Consignor), ref fConsignor, value); }
        }
        bool fCarrier;
        public bool Carrier
        {
            get { return fCarrier; }
            set { SetPropertyValue<bool>(nameof(Carrier), ref fCarrier, value); }
        }
        bool fConsignee;
        public bool Consignee
        {
            get { return fConsignee; }
            set { SetPropertyValue<bool>(nameof(Consignee), ref fConsignee, value); }
        }
        bool fLoader;
        public bool Loader
        {
            get { return fLoader; }
            set { SetPropertyValue<bool>(nameof(Loader), ref fLoader, value); }
        }
        bool fUnloader;
        public bool Unloader
        {
            get { return fUnloader; }
            set { SetPropertyValue<bool>(nameof(Unloader), ref fUnloader, value); }
        }
        bool fPacker;
        public bool Packer
        {
            get { return fPacker; }
            set { SetPropertyValue<bool>(nameof(Packer), ref fPacker, value); }
        }
        bool fFiller;
        public bool Filler
        {
            get { return fFiller; }
            set { SetPropertyValue<bool>(nameof(Filler), ref fFiller, value); }
        }
        bool fTankContainer;
        public bool TankContainer
        {
            get { return fTankContainer; }
            set { SetPropertyValue<bool>(nameof(TankContainer), ref fTankContainer, value); }
        }
        string fPackagingQuantityUnit;
        public string PackagingQuantityUnit
        {
            get { return fPackagingQuantityUnit; }
            set { SetPropertyValue<string>(nameof(PackagingQuantityUnit), ref fPackagingQuantityUnit, value); }
        }
        string fLastYearIntakeUnit;
        public string LastYearIntakeUnit
        {
            get { return fLastYearIntakeUnit; }
            set { SetPropertyValue<string>(nameof(LastYearIntakeUnit), ref fLastYearIntakeUnit, value); }
        }
        PackingGroup fPackingGroup;
        [Association(@"CustomerInventoryReferencesPackingGroup")]
        public PackingGroup PackingGroup
        {
            get { return fPackingGroup; }
            set { SetPropertyValue<PackingGroup>(nameof(PackingGroup), ref fPackingGroup, value); }
        }
        byte[] fLabelImage1;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] LabelImage1
        {
            get { return fLabelImage1; }
            set { SetPropertyValue<byte[]>(nameof(LabelImage1), ref fLabelImage1, value); }
        }
        byte[] fLabelImage2;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] LabelImage2
        {
            get { return fLabelImage2; }
            set { SetPropertyValue<byte[]>(nameof(LabelImage2), ref fLabelImage2, value); }
        }
        byte[] fLabelImage3;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] LabelImage3
        {
            get { return fLabelImage3; }
            set { SetPropertyValue<byte[]>(nameof(LabelImage3), ref fLabelImage3, value); }
        }
        byte[] fLabelImage4;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] LabelImage4
        {
            get { return fLabelImage4; }
            set { SetPropertyValue<byte[]>(nameof(LabelImage4), ref fLabelImage4, value); }
        }
        string fShipper;
        public string Shipper
        {
            get { return fShipper; }
            set { SetPropertyValue<string>(nameof(Shipper), ref fShipper, value); }
        }
        string fMSDSName;
        public string MSDSName
        {
            get { return fMSDSName; }
            set { SetPropertyValue<string>(nameof(MSDSName), ref fMSDSName, value); }
        }
        PackagingTypes fPackagingTypes;
        [Association(@"CustomerInventoryReferencesPackagingTypes")]
        public PackagingTypes PackagingTypes
        {
            get { return fPackagingTypes; }
            set { SetPropertyValue<PackagingTypes>(nameof(PackagingTypes), ref fPackagingTypes, value); }
        }
    }

}
