//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class Education : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        string fSubject;
        public string Subject
        {
            get { return fSubject; }
            set { SetPropertyValue<string>(nameof(Subject), ref fSubject, value); }
        }
        Employee fInstructur;
        [Association(@"EducationReferencesEmployee")]
        public Employee Instructur
        {
            get { return fInstructur; }
            set { SetPropertyValue<Employee>(nameof(Instructur), ref fInstructur, value); }
        }
        Customer fCustomer;
        [Association(@"EducationReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        string fLocation;
        public string Location
        {
            get { return fLocation; }
            set { SetPropertyValue<string>(nameof(Location), ref fLocation, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        [Association(@"ParticipantReferencesEducation")]
        public XPCollection<Participant> Participants { get { return GetCollection<Participant>(nameof(Participants)); } }
    }

}
