//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class EMailSetting : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fFromMailAddress;
        public string FromMailAddress
        {
            get { return fFromMailAddress; }
            set { SetPropertyValue<string>(nameof(FromMailAddress), ref fFromMailAddress, value); }
        }
        string fFromMailAddressPassword;
        public string FromMailAddressPassword
        {
            get { return fFromMailAddressPassword; }
            set { SetPropertyValue<string>(nameof(FromMailAddressPassword), ref fFromMailAddressPassword, value); }
        }
        int fPort;
        public int Port
        {
            get { return fPort; }
            set { SetPropertyValue<int>(nameof(Port), ref fPort, value); }
        }
        bool fUseSSL;
        public bool UseSSL
        {
            get { return fUseSSL; }
            set { SetPropertyValue<bool>(nameof(UseSSL), ref fUseSSL, value); }
        }
        string fSMTPAddress;
        public string SMTPAddress
        {
            get { return fSMTPAddress; }
            set { SetPropertyValue<string>(nameof(SMTPAddress), ref fSMTPAddress, value); }
        }
        bool fIsActive;
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
    }

}
