//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class EmployeeRole : PermissionPolicyRole
    {
        [Association(@"EmployeeRoleEmployeeRoles_EmployeeEmployeesReferencesEmployeeRole")]
        public XPCollection<EmployeeRoleEmployeeRoles_EmployeeEmployees> EmployeeRoleEmployeeRoles_EmployeeEmployeess { get { return GetCollection<EmployeeRoleEmployeeRoles_EmployeeEmployees>(nameof(EmployeeRoleEmployeeRoles_EmployeeEmployeess)); } }
    }

}
