//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class EstimatedQuantityOfLossOfProduct : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        HazardousGoodsClass fClass;
        [Association(@"EstimatedQuantityOfLossOfProductReferencesHazardousGoodsClass")]
        public HazardousGoodsClass Class
        {
            get { return fClass; }
            set { SetPropertyValue<HazardousGoodsClass>(nameof(Class), ref fClass, value); }
        }
        [Association(@"DangerousGoodInvolvedReferencesEstimatedQuantityOfLossOfProduct")]
        public XPCollection<DangerousGoodInvolved> DangerousGoodInvolveds { get { return GetCollection<DangerousGoodInvolved>(nameof(DangerousGoodInvolveds)); } }
    }

}
