//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class HazardousGoodsPackingInstructionPackingInstructions_HazardousGoodsHazardousGoods : XPBaseObject
    {
        HazardousGoods fHazardousGoods;
        [Indexed(@"PackingInstructions", Name = @"iHazardousGoodsPackingInstructions_HazardousGoodsPackingInstructionPackingInstructions_HazardousGoodsHazardousGoods", Unique = true)]
        [Association(@"HazardousGoodsPackingInstructionPackingInstructions_HazardousGoodsHazardousGoodsReferencesHazardousGoods")]
        public HazardousGoods HazardousGoods
        {
            get { return fHazardousGoods; }
            set { SetPropertyValue<HazardousGoods>(nameof(HazardousGoods), ref fHazardousGoods, value); }
        }
        HazardousGoodsPackingInstruction fPackingInstructions;
        [Association(@"HazardousGoodsPackingInstructionPackingInstructions_HazardousGoodsHazardousGoodsReferencesHazardousGoodsPackingInstruction")]
        public HazardousGoodsPackingInstruction PackingInstructions
        {
            get { return fPackingInstructions; }
            set { SetPropertyValue<HazardousGoodsPackingInstruction>(nameof(PackingInstructions), ref fPackingInstructions, value); }
        }
        Guid fOID;
        [Key(true)]
        public Guid OID
        {
            get { return fOID; }
            set { SetPropertyValue<Guid>(nameof(OID), ref fOID, value); }
        }
    }

}
