//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class HazardousGoodsClass : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fName;
        [Size(200)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        HazardousGoodsClass fParentHazardousGoodsClass;
        [Association(@"HazardousGoodsClassReferencesHazardousGoodsClass")]
        public HazardousGoodsClass ParentHazardousGoodsClass
        {
            get { return fParentHazardousGoodsClass; }
            set { SetPropertyValue<HazardousGoodsClass>(nameof(ParentHazardousGoodsClass), ref fParentHazardousGoodsClass, value); }
        }
        HazardousGoods fHazardousGoods;
        [Association(@"HazardousGoodsClassReferencesHazardousGoods")]
        public HazardousGoods HazardousGoods
        {
            get { return fHazardousGoods; }
            set { SetPropertyValue<HazardousGoods>(nameof(HazardousGoods), ref fHazardousGoods, value); }
        }
        [Association(@"ActivityReportTransactionReferencesHazardousGoodsClass")]
        public XPCollection<ActivityReportTransaction> ActivityReportTransactions { get { return GetCollection<ActivityReportTransaction>(nameof(ActivityReportTransactions)); } }
        [Association(@"DangerousGoodInvolvedReferencesHazardousGoodsClass")]
        public XPCollection<DangerousGoodInvolved> DangerousGoodInvolveds { get { return GetCollection<DangerousGoodInvolved>(nameof(DangerousGoodInvolveds)); } }
        [Association(@"EstimatedQuantityOfLossOfProductReferencesHazardousGoodsClass")]
        public XPCollection<EstimatedQuantityOfLossOfProduct> EstimatedQuantityOfLossOfProducts { get { return GetCollection<EstimatedQuantityOfLossOfProduct>(nameof(EstimatedQuantityOfLossOfProducts)); } }
        [Association(@"HazardousGoodsReferencesHazardousGoodsClass")]
        public XPCollection<HazardousGoods> HazardousGoodsCollection { get { return GetCollection<HazardousGoods>(nameof(HazardousGoodsCollection)); } }
        [Association(@"HazardousGoodsClassReferencesHazardousGoodsClass")]
        public XPCollection<HazardousGoodsClass> HazardousGoodsClassCollection { get { return GetCollection<HazardousGoodsClass>(nameof(HazardousGoodsClassCollection)); } }
        [Association(@"HazardousGoodsHazardousGoods_HazardousGoodsClassClassesReferencesHazardousGoodsClass")]
        public XPCollection<HazardousGoodsHazardousGoods_HazardousGoodsClassClasses> HazardousGoodsHazardousGoods_HazardousGoodsClassClassess { get { return GetCollection<HazardousGoodsHazardousGoods_HazardousGoodsClassClasses>(nameof(HazardousGoodsHazardousGoods_HazardousGoodsClassClassess)); } }
        [Association(@"TransportDocumentOtherTransactionReferencesHazardousGoodsClass")]
        public XPCollection<TransportDocumentOtherTransaction> TransportDocumentOtherTransactions { get { return GetCollection<TransportDocumentOtherTransaction>(nameof(TransportDocumentOtherTransactions)); } }
        [Association(@"TransportDocumentTransactionReferencesHazardousGoodsClass")]
        public XPCollection<TransportDocumentTransaction> TransportDocumentTransactions { get { return GetCollection<TransportDocumentTransaction>(nameof(TransportDocumentTransactions)); } }
    }

}
