//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class HazardousGoodsSpecialProvisionForCarriageLUHSpecialProvisionForCarriageLoadingUnloadingAndHandling_HazardousGoodsHazardousGoods : XPBaseObject
    {
        HazardousGoods fHazardousGoods;
        [Indexed(@"SpecialProvisionForCarriageLoadingUnloadingAndHandling", Name = @"iHazardousGoodsSpecialProvisionForCarriageLoadingUnloadingAndHandling_HazardousGoodsSpecialProvisionForCarriageLUHSpeci_8D49571A", Unique = true)]
        [Association(@"HazardousGoodsSpecialProvisionForCarriageLUHSpecialProvisionForCarriageLoadingUnloadingAndHandling_HazardousGoodsHazardousGoodsReferencesHazardousGoods")]
        public HazardousGoods HazardousGoods
        {
            get { return fHazardousGoods; }
            set { SetPropertyValue<HazardousGoods>(nameof(HazardousGoods), ref fHazardousGoods, value); }
        }
        HazardousGoodsSpecialProvisionForCarriageLUH fSpecialProvisionForCarriageLoadingUnloadingAndHandling;
        [Association(@"HazardousGoodsSpecialProvisionForCarriageLUHSpecialProvisionForCarriageLoadingUnloadingAndHandling_HazardousGoodsHazardousGoodsReferencesHazardousGoodsSpecialProvisionForCarriageLUH")]
        public HazardousGoodsSpecialProvisionForCarriageLUH SpecialProvisionForCarriageLoadingUnloadingAndHandling
        {
            get { return fSpecialProvisionForCarriageLoadingUnloadingAndHandling; }
            set { SetPropertyValue<HazardousGoodsSpecialProvisionForCarriageLUH>(nameof(SpecialProvisionForCarriageLoadingUnloadingAndHandling), ref fSpecialProvisionForCarriageLoadingUnloadingAndHandling, value); }
        }
        Guid fOID;
        [Key(true)]
        public Guid OID
        {
            get { return fOID; }
            set { SetPropertyValue<Guid>(nameof(OID), ref fOID, value); }
        }
    }

}
