//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class HazardousGoodsSpecialProvisionForCarriageBulkSpecialProvisionForCarriageBulk_HazardousGoodsHazardousGoods : XPBaseObject
    {
        HazardousGoods fHazardousGoods;
        [Indexed(@"SpecialProvisionForCarriageBulk", Name = @"iHazardousGoodsSpecialProvisionForCarriageBulk_HazardousGoodsSpecialProvisionForCarriageBulkSpecialProvisionForCarriage_1FF22DDD", Unique = true)]
        [Association(@"HazardousGoodsSpecialProvisionForCarriageBulkSpecialProvisionForCarriageBulk_HazardousGoodsHazardousGoodsReferencesHazardousGoods")]
        public HazardousGoods HazardousGoods
        {
            get { return fHazardousGoods; }
            set { SetPropertyValue<HazardousGoods>(nameof(HazardousGoods), ref fHazardousGoods, value); }
        }
        HazardousGoodsSpecialProvisionForCarriageBulk fSpecialProvisionForCarriageBulk;
        [Association(@"HazardousGoodsSpecialProvisionForCarriageBulkSpecialProvisionForCarriageBulk_HazardousGoodsHazardousGoodsReferencesHazardousGoodsSpecialProvisionForCarriageBulk")]
        public HazardousGoodsSpecialProvisionForCarriageBulk SpecialProvisionForCarriageBulk
        {
            get { return fSpecialProvisionForCarriageBulk; }
            set { SetPropertyValue<HazardousGoodsSpecialProvisionForCarriageBulk>(nameof(SpecialProvisionForCarriageBulk), ref fSpecialProvisionForCarriageBulk, value); }
        }
        Guid fOID;
        [Key(true)]
        public Guid OID
        {
            get { return fOID; }
            set { SetPropertyValue<Guid>(nameof(OID), ref fOID, value); }
        }
    }

}
