//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class HazardousGoodsHazardousGoods_HazardousGoodsADRTankCodeADRTankCodes : XPBaseObject
    {
        HazardousGoodsADRTankCode fADRTankCodes;
        [Indexed(@"HazardousGoods", Name = @"iADRTankCodesHazardousGoods_HazardousGoodsHazardousGoods_HazardousGoodsADRTankCodeADRTankCodes", Unique = true)]
        [Association(@"HazardousGoodsHazardousGoods_HazardousGoodsADRTankCodeADRTankCodesReferencesHazardousGoodsADRTankCode")]
        public HazardousGoodsADRTankCode ADRTankCodes
        {
            get { return fADRTankCodes; }
            set { SetPropertyValue<HazardousGoodsADRTankCode>(nameof(ADRTankCodes), ref fADRTankCodes, value); }
        }
        HazardousGoods fHazardousGoods;
        [Association(@"HazardousGoodsHazardousGoods_HazardousGoodsADRTankCodeADRTankCodesReferencesHazardousGoods")]
        public HazardousGoods HazardousGoods
        {
            get { return fHazardousGoods; }
            set { SetPropertyValue<HazardousGoods>(nameof(HazardousGoods), ref fHazardousGoods, value); }
        }
        Guid fOID;
        [Key(true)]
        public Guid OID
        {
            get { return fOID; }
            set { SetPropertyValue<Guid>(nameof(OID), ref fOID, value); }
        }
    }

}
