//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class iEvent : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fResourceIds;
        [Size(SizeAttribute.Unlimited)]
        public string ResourceIds
        {
            get { return fResourceIds; }
            set { SetPropertyValue<string>(nameof(ResourceIds), ref fResourceIds, value); }
        }
        iEvent fRecurrencePattern;
        [Association(@"iEventReferencesiEvent")]
        public iEvent RecurrencePattern
        {
            get { return fRecurrencePattern; }
            set { SetPropertyValue<iEvent>(nameof(RecurrencePattern), ref fRecurrencePattern, value); }
        }
        bool fAllDay;
        public bool AllDay
        {
            get { return fAllDay; }
            set { SetPropertyValue<bool>(nameof(AllDay), ref fAllDay, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        int fLabel;
        public int Label
        {
            get { return fLabel; }
            set { SetPropertyValue<int>(nameof(Label), ref fLabel, value); }
        }
        string fLocation;
        public string Location
        {
            get { return fLocation; }
            set { SetPropertyValue<string>(nameof(Location), ref fLocation, value); }
        }
        DateTime fStartOn;
        [Indexed(Name = @"iStartOn_iEvent")]
        public DateTime StartOn
        {
            get { return fStartOn; }
            set { SetPropertyValue<DateTime>(nameof(StartOn), ref fStartOn, value); }
        }
        DateTime fEndOn;
        [Indexed(Name = @"iEndOn_iEvent")]
        public DateTime EndOn
        {
            get { return fEndOn; }
            set { SetPropertyValue<DateTime>(nameof(EndOn), ref fEndOn, value); }
        }
        int fStatus;
        public int Status
        {
            get { return fStatus; }
            set { SetPropertyValue<int>(nameof(Status), ref fStatus, value); }
        }
        string fSubject;
        [Size(250)]
        public string Subject
        {
            get { return fSubject; }
            set { SetPropertyValue<string>(nameof(Subject), ref fSubject, value); }
        }
        int fType;
        public int Type
        {
            get { return fType; }
            set { SetPropertyValue<int>(nameof(Type), ref fType, value); }
        }
        string fRecurrenceInfoXml;
        [Size(SizeAttribute.Unlimited)]
        public string RecurrenceInfoXml
        {
            get { return fRecurrenceInfoXml; }
            set { SetPropertyValue<string>(nameof(RecurrenceInfoXml), ref fRecurrenceInfoXml, value); }
        }
        DateTime fAlarmTime;
        public DateTime AlarmTime
        {
            get { return fAlarmTime; }
            set { SetPropertyValue<DateTime>(nameof(AlarmTime), ref fAlarmTime, value); }
        }
        bool fIsPostponed;
        public bool IsPostponed
        {
            get { return fIsPostponed; }
            set { SetPropertyValue<bool>(nameof(IsPostponed), ref fIsPostponed, value); }
        }
        double fRemindIn;
        public double RemindIn
        {
            get { return fRemindIn; }
            set { SetPropertyValue<double>(nameof(RemindIn), ref fRemindIn, value); }
        }
        Employee fOwner;
        [Association(@"iEventReferencesEmployee")]
        public Employee Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<Employee>(nameof(Owner), ref fOwner, value); }
        }
        [Association(@"iEventReferencesiEvent")]
        public XPCollection<iEvent> iEventCollection { get { return GetCollection<iEvent>(nameof(iEventCollection)); } }
        [Association(@"iEvent_EmployeesReferencesiEvent")]
        public XPCollection<iEvent_Employees> iEvent_Employeess { get { return GetCollection<iEvent_Employees>(nameof(iEvent_Employeess)); } }
    }

}
