//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class Participant : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        Education fEducation;
        [Association(@"ParticipantReferencesEducation")]
        public Education Education
        {
            get { return fEducation; }
            set { SetPropertyValue<Education>(nameof(Education), ref fEducation, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fTCKN;
        [Size(11)]
        public string TCKN
        {
            get { return fTCKN; }
            set { SetPropertyValue<string>(nameof(TCKN), ref fTCKN, value); }
        }
        double fDegree;
        public double Degree
        {
            get { return fDegree; }
            set { SetPropertyValue<double>(nameof(Degree), ref fDegree, value); }
        }
        int fLineNumber;
        public int LineNumber
        {
            get { return fLineNumber; }
            set { SetPropertyValue<int>(nameof(LineNumber), ref fLineNumber, value); }
        }
    }

}
