//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class PermissionPolicyRole : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        bool fIsAdministrative;
        public bool IsAdministrative
        {
            get { return fIsAdministrative; }
            set { SetPropertyValue<bool>(nameof(IsAdministrative), ref fIsAdministrative, value); }
        }
        bool fCanEditModel;
        public bool CanEditModel
        {
            get { return fCanEditModel; }
            set { SetPropertyValue<bool>(nameof(CanEditModel), ref fCanEditModel, value); }
        }
        int fPermissionPolicy;
        public int PermissionPolicy
        {
            get { return fPermissionPolicy; }
            set { SetPropertyValue<int>(nameof(PermissionPolicy), ref fPermissionPolicy, value); }
        }
        [Association(@"PermissionPolicyActionPermissionObjectReferencesPermissionPolicyRole")]
        public XPCollection<PermissionPolicyActionPermissionObject> PermissionPolicyActionPermissionObjects { get { return GetCollection<PermissionPolicyActionPermissionObject>(nameof(PermissionPolicyActionPermissionObjects)); } }
        [Association(@"PermissionPolicyNavigationPermissionsObjectReferencesPermissionPolicyRole")]
        public XPCollection<PermissionPolicyNavigationPermissionsObject> PermissionPolicyNavigationPermissionsObjects { get { return GetCollection<PermissionPolicyNavigationPermissionsObject>(nameof(PermissionPolicyNavigationPermissionsObjects)); } }
        [Association(@"PermissionPolicyTypePermissionsObjectReferencesPermissionPolicyRole")]
        public XPCollection<PermissionPolicyTypePermissionsObject> PermissionPolicyTypePermissionsObjects { get { return GetCollection<PermissionPolicyTypePermissionsObject>(nameof(PermissionPolicyTypePermissionsObjects)); } }
    }

}
