//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class VehicleControlDocument : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        Employee fOwner;
        [Association(@"VehicleControlDocumentReferencesEmployee")]
        public Employee Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<Employee>(nameof(Owner), ref fOwner, value); }
        }
        int fVControlOption;
        public int VControlOption
        {
            get { return fVControlOption; }
            set { SetPropertyValue<int>(nameof(VControlOption), ref fVControlOption, value); }
        }
        Customer fConsigner;
        [Association(@"VehicleControlDocumentReferencesCustomer")]
        public Customer Consigner
        {
            get { return fConsigner; }
            set { SetPropertyValue<Customer>(nameof(Consigner), ref fConsigner, value); }
        }
        string fDeliveryCompany;
        public string DeliveryCompany
        {
            get { return fDeliveryCompany; }
            set { SetPropertyValue<string>(nameof(DeliveryCompany), ref fDeliveryCompany, value); }
        }
        Vehicle fVehicle;
        [Association(@"VehicleControlDocumentReferencesVehicle")]
        public Vehicle Vehicle
        {
            get { return fVehicle; }
            set { SetPropertyValue<Vehicle>(nameof(Vehicle), ref fVehicle, value); }
        }
        VehicleDriver fVehicleDriver;
        [Association(@"VehicleControlDocumentReferencesVehicleDriver")]
        public VehicleDriver VehicleDriver
        {
            get { return fVehicleDriver; }
            set { SetPropertyValue<VehicleDriver>(nameof(VehicleDriver), ref fVehicleDriver, value); }
        }
        DateTime fSRCDateOfValidity;
        public DateTime SRCDateOfValidity
        {
            get { return fSRCDateOfValidity; }
            set { SetPropertyValue<DateTime>(nameof(SRCDateOfValidity), ref fSRCDateOfValidity, value); }
        }
        DateTime fInsurancePolicy;
        public DateTime InsurancePolicy
        {
            get { return fInsurancePolicy; }
            set { SetPropertyValue<DateTime>(nameof(InsurancePolicy), ref fInsurancePolicy, value); }
        }
        double fMaxWeight;
        public double MaxWeight
        {
            get { return fMaxWeight; }
            set { SetPropertyValue<double>(nameof(MaxWeight), ref fMaxWeight, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        [Association(@"VehicleControlDocumentTransactionReferencesVehicleControlDocument")]
        public XPCollection<VehicleControlDocumentTransaction> VehicleControlDocumentTransactions { get { return GetCollection<VehicleControlDocumentTransaction>(nameof(VehicleControlDocumentTransactions)); } }
    }

}
