//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.API.Models.iyibir_TMGD
{

    public partial class WasteList : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fName;
        [Size(SizeAttribute.Unlimited)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        int fWasteType;
        public int WasteType
        {
            get { return fWasteType; }
            set { SetPropertyValue<int>(nameof(WasteType), ref fWasteType, value); }
        }
        [Association(@"CustomerWasteInventoryReferencesWasteList")]
        public XPCollection<CustomerWasteInventory> CustomerWasteInventories { get { return GetCollection<CustomerWasteInventory>(nameof(CustomerWasteInventories)); } }
        [Association(@"TransportDocumentOtherTransactionReferencesWasteList")]
        public XPCollection<TransportDocumentOtherTransaction> TransportDocumentOtherTransactions { get { return GetCollection<TransportDocumentOtherTransaction>(nameof(TransportDocumentOtherTransactions)); } }
    }

}
