<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<CheckEolTargetFramework>false</CheckEolTargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<ApplicationIcon>ExpressApp.ico</ApplicationIcon>
		<Deterministic>false</Deterministic>
		<AssemblyVersion>1.0.*</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<Configurations>Debug;Release;EasyTest</Configurations>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="Images\Logo.svg" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="favicon.ico">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<EmbeddedResource Include="Images\ReadMe.txt" />
		<EmbeddedResource Include="Images\SplashScreen.svg">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</EmbeddedResource>
		<Content Include="Model.xafml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Model_tr.xafml">
			<DependentUpon>Model.xafml</DependentUpon>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>

		<PackageReference Include="DevExpress.ExpressApp" Version="25.2.3" />
		<PackageReference Include="DevExpress.ExpressApp.Chart.Win" Version="25.2.3" />
		<PackageReference Include="DevExpress.ExpressApp.CodeAnalysis" Version="25.2.3" />
		<PackageReference Include="DevExpress.ExpressApp.Dashboards.Win" Version="25.2.3" />
		<PackageReference Include="DevExpress.ExpressApp.FileAttachment.Win" Version="25.2.3" />
		<PackageReference Include="DevExpress.ExpressApp.Security.Xpo" Version="25.2.3" />
		<PackageReference Include="DevExpress.ExpressApp.Validation.Win" Version="25.2.3" />
		<PackageReference Include="DevExpress.ExpressApp.Win" Version="25.2.3" />
		<PackageReference Include="DevExpress.ExpressApp.Win.Design" Version="25.2.3" />
		<PackageReference Include="DevExpress.ExpressApp.Xpo" Version="25.2.3" />
		<PackageReference Include="DevExpress.Persistent.Base" Version="25.2.3" />
		<PackageReference Include="DevExpress.Persistent.BaseImpl.Xpo" Version="25.2.3" />
		<PackageReference Include="DevExpress.RichEdit.Export" Version="25.2.3" />
		<PackageReference Include="DevExpress.Win.Design" Version="25.2.3" />
		<PackageReference Include="DevExpress.ExpressApp.Scheduler.Win" Version="25.2.3" />
		<PackageReference Include="DevExpress.ExpressApp.ReportsV2.Win" Version="25.2.3" />
		<PackageReference Include="DevExpress.ExpressApp.TreeListEditors.Win" Version="25.2.3" />

	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\iyibir.TMGD.Module\iyibir.TMGD.Module.csproj" />
	</ItemGroup>

</Project>