//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class AnnualWorkPlan : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        Customer fCustomer;
        [Association(@"AnnualWorkPlanReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        CustomerContact fCustomerContact;
        [Association(@"AnnualWorkPlanReferencesCustomerContact")]
        public CustomerContact CustomerContact
        {
            get { return fCustomerContact; }
            set { SetPropertyValue<CustomerContact>(nameof(CustomerContact), ref fCustomerContact, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        Employee fOwner;
        [Association(@"AnnualWorkPlanReferencesEmployee")]
        public Employee Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<Employee>(nameof(Owner), ref fOwner, value); }
        }
        [Association(@"AnnualWorkPlanSubjectReferencesAnnualWorkPlan")]
        public XPCollection<AnnualWorkPlanSubject> AnnualWorkPlanSubjects { get { return GetCollection<AnnualWorkPlanSubject>(nameof(AnnualWorkPlanSubjects)); } }
    }

}
