//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class AuditDeterminationLegalStatute : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        AuditDeterminationForm fAuditDeterminationForm;
        [Association(@"AuditDeterminationLegalStatuteReferencesAuditDeterminationForm")]
        public AuditDeterminationForm AuditDeterminationForm
        {
            get { return fAuditDeterminationForm; }
            set { SetPropertyValue<AuditDeterminationForm>(nameof(AuditDeterminationForm), ref fAuditDeterminationForm, value); }
        }
        string fLegalStatute;
        [Size(SizeAttribute.Unlimited)]
        public string LegalStatute
        {
            get { return fLegalStatute; }
            set { SetPropertyValue<string>(nameof(LegalStatute), ref fLegalStatute, value); }
        }
        DefaultLegalLegislation fDefaultLegalLegislation;
        [Association(@"AuditDeterminationLegalStatuteReferencesDefaultLegalLegislation")]
        public DefaultLegalLegislation DefaultLegalLegislation
        {
            get { return fDefaultLegalLegislation; }
            set { SetPropertyValue<DefaultLegalLegislation>(nameof(DefaultLegalLegislation), ref fDefaultLegalLegislation, value); }
        }
        [Association(@"AuditDeterminationLegalStatuteTransactionReferencesAuditDeterminationLegalStatute")]
        public XPCollection<AuditDeterminationLegalStatuteTransaction> AuditDeterminationLegalStatuteTransactions { get { return GetCollection<AuditDeterminationLegalStatuteTransaction>(nameof(AuditDeterminationLegalStatuteTransactions)); } }
    }

}
