//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class CASNumber : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        int fCASType;
        public int CASType
        {
            get { return fCASType; }
            set { SetPropertyValue<int>(nameof(CASType), ref fCASType, value); }
        }
        [Association(@"ProductCASNumberReferencesCASNumber")]
        public XPCollection<ProductCASNumber> ProductCASNumbers { get { return GetCollection<ProductCASNumber>(nameof(ProductCASNumbers)); } }
    }

}
