//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class Contract : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        Employee fOwner;
        [Association(@"ContractReferencesEmployee")]
        public Employee Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<Employee>(nameof(Owner), ref fOwner, value); }
        }
        Company fCompany;
        [Association(@"ContractReferencesCompany")]
        public Company Company
        {
            get { return fCompany; }
            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        }
        Customer fCustomer;
        [Association(@"ContractReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        int fTaskDay;
        public int TaskDay
        {
            get { return fTaskDay; }
            set { SetPropertyValue<int>(nameof(TaskDay), ref fTaskDay, value); }
        }
        double fProcessPrice;
        public double ProcessPrice
        {
            get { return fProcessPrice; }
            set { SetPropertyValue<double>(nameof(ProcessPrice), ref fProcessPrice, value); }
        }
        double fServicePrice;
        public double ServicePrice
        {
            get { return fServicePrice; }
            set { SetPropertyValue<double>(nameof(ServicePrice), ref fServicePrice, value); }
        }
        double fEducationPrice;
        public double EducationPrice
        {
            get { return fEducationPrice; }
            set { SetPropertyValue<double>(nameof(EducationPrice), ref fEducationPrice, value); }
        }
        DateTime fModificationDate;
        public DateTime ModificationDate
        {
            get { return fModificationDate; }
            set { SetPropertyValue<DateTime>(nameof(ModificationDate), ref fModificationDate, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
    }

}
