//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class Country : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        [Association(@"CityReferencesCountry")]
        public XPCollection<City> Cities { get { return GetCollection<City>(nameof(Cities)); } }
        [Association(@"CompanyReferencesCountry")]
        public XPCollection<Company> Companies { get { return GetCollection<Company>(nameof(Companies)); } }
        [Association(@"ConsigneeReferencesCountry")]
        public XPCollection<Consignee> Consignees { get { return GetCollection<Consignee>(nameof(Consignees)); } }
        [Association(@"CustomerReferencesCountry")]
        public XPCollection<Customer> Customers { get { return GetCollection<Customer>(nameof(Customers)); } }
        [Association(@"CustomerContactReferencesCountry")]
        public XPCollection<CustomerContact> CustomerContacts { get { return GetCollection<CustomerContact>(nameof(CustomerContacts)); } }
        [Association(@"LeadReferencesCountry")]
        public XPCollection<Lead> Leads { get { return GetCollection<Lead>(nameof(Leads)); } }
    }

}
