//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class CustomerContact : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        Customer fCustomer;
        [Association(@"CustomerContactReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        Country fCountry;
        [Association(@"CustomerContactReferencesCountry")]
        public Country Country
        {
            get { return fCountry; }
            set { SetPropertyValue<Country>(nameof(Country), ref fCountry, value); }
        }
        City fCity;
        [Association(@"CustomerContactReferencesCity")]
        public City City
        {
            get { return fCity; }
            set { SetPropertyValue<City>(nameof(City), ref fCity, value); }
        }
        County fCounty;
        [Association(@"CustomerContactReferencesCounty")]
        public County County
        {
            get { return fCounty; }
            set { SetPropertyValue<County>(nameof(County), ref fCounty, value); }
        }
        string fTelephone;
        public string Telephone
        {
            get { return fTelephone; }
            set { SetPropertyValue<string>(nameof(Telephone), ref fTelephone, value); }
        }
        string fOtherTelephone;
        public string OtherTelephone
        {
            get { return fOtherTelephone; }
            set { SetPropertyValue<string>(nameof(OtherTelephone), ref fOtherTelephone, value); }
        }
        string fEMail;
        public string EMail
        {
            get { return fEMail; }
            set { SetPropertyValue<string>(nameof(EMail), ref fEMail, value); }
        }
        string fAddress;
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        bool fIsActive;
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        string fTCKN;
        [Size(11)]
        public string TCKN
        {
            get { return fTCKN; }
            set { SetPropertyValue<string>(nameof(TCKN), ref fTCKN, value); }
        }
        string fRegistrationNumber;
        public string RegistrationNumber
        {
            get { return fRegistrationNumber; }
            set { SetPropertyValue<string>(nameof(RegistrationNumber), ref fRegistrationNumber, value); }
        }
        string feGovernmentAuthorized;
        public string eGovernmentAuthorized
        {
            get { return feGovernmentAuthorized; }
            set { SetPropertyValue<string>(nameof(eGovernmentAuthorized), ref feGovernmentAuthorized, value); }
        }
        [Association(@"ActivityReferencesCustomerContact")]
        public XPCollection<Activity> Activities { get { return GetCollection<Activity>(nameof(Activities)); } }
        [Association(@"AnnualWorkPlanReferencesCustomerContact")]
        public XPCollection<AnnualWorkPlan> AnnualWorkPlans { get { return GetCollection<AnnualWorkPlan>(nameof(AnnualWorkPlans)); } }
        [Association(@"AuditDeterminationFormReferencesCustomerContact")]
        public XPCollection<AuditDeterminationForm> AuditDeterminationForms { get { return GetCollection<AuditDeterminationForm>(nameof(AuditDeterminationForms)); } }
        [Association(@"DistributionOfTaskReferencesCustomerContact")]
        public XPCollection<DistributionOfTask> DistributionOfTasks { get { return GetCollection<DistributionOfTask>(nameof(DistributionOfTasks)); } }
    }

}
