//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class Customer : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        byte[] fCustomerImage;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] CustomerImage
        {
            get { return fCustomerImage; }
            set { SetPropertyValue<byte[]>(nameof(CustomerImage), ref fCustomerImage, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fTitle;
        public string Title
        {
            get { return fTitle; }
            set { SetPropertyValue<string>(nameof(Title), ref fTitle, value); }
        }
        Country fCountry;
        [Association(@"CustomerReferencesCountry")]
        public Country Country
        {
            get { return fCountry; }
            set { SetPropertyValue<Country>(nameof(Country), ref fCountry, value); }
        }
        City fCity;
        [Association(@"CustomerReferencesCity")]
        public City City
        {
            get { return fCity; }
            set { SetPropertyValue<City>(nameof(City), ref fCity, value); }
        }
        County fCounty;
        [Association(@"CustomerReferencesCounty")]
        public County County
        {
            get { return fCounty; }
            set { SetPropertyValue<County>(nameof(County), ref fCounty, value); }
        }
        string fTelephone;
        public string Telephone
        {
            get { return fTelephone; }
            set { SetPropertyValue<string>(nameof(Telephone), ref fTelephone, value); }
        }
        string fOtherTelephone;
        public string OtherTelephone
        {
            get { return fOtherTelephone; }
            set { SetPropertyValue<string>(nameof(OtherTelephone), ref fOtherTelephone, value); }
        }
        string fEMail;
        public string EMail
        {
            get { return fEMail; }
            set { SetPropertyValue<string>(nameof(EMail), ref fEMail, value); }
        }
        string fAddress;
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        bool fIsActive;
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        bool fIsPerson;
        public bool IsPerson
        {
            get { return fIsPerson; }
            set { SetPropertyValue<bool>(nameof(IsPerson), ref fIsPerson, value); }
        }
        string fTCKN;
        [Size(11)]
        public string TCKN
        {
            get { return fTCKN; }
            set { SetPropertyValue<string>(nameof(TCKN), ref fTCKN, value); }
        }
        string fFirstName;
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
        }
        string fLastName;
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>(nameof(LastName), ref fLastName, value); }
        }
        bool fConsignor;
        public bool Consignor
        {
            get { return fConsignor; }
            set { SetPropertyValue<bool>(nameof(Consignor), ref fConsignor, value); }
        }
        bool fCarrier;
        public bool Carrier
        {
            get { return fCarrier; }
            set { SetPropertyValue<bool>(nameof(Carrier), ref fCarrier, value); }
        }
        bool fConsignee;
        public bool Consignee
        {
            get { return fConsignee; }
            set { SetPropertyValue<bool>(nameof(Consignee), ref fConsignee, value); }
        }
        bool fLoader;
        public bool Loader
        {
            get { return fLoader; }
            set { SetPropertyValue<bool>(nameof(Loader), ref fLoader, value); }
        }
        bool fUnloader;
        public bool Unloader
        {
            get { return fUnloader; }
            set { SetPropertyValue<bool>(nameof(Unloader), ref fUnloader, value); }
        }
        bool fPacker;
        public bool Packer
        {
            get { return fPacker; }
            set { SetPropertyValue<bool>(nameof(Packer), ref fPacker, value); }
        }
        bool fFiller;
        public bool Filler
        {
            get { return fFiller; }
            set { SetPropertyValue<bool>(nameof(Filler), ref fFiller, value); }
        }
        bool fTankContainer;
        public bool TankContainer
        {
            get { return fTankContainer; }
            set { SetPropertyValue<bool>(nameof(TankContainer), ref fTankContainer, value); }
        }
        FileData fActivityCertificate;
        [Association(@"CustomerReferencesFileData")]
        public FileData ActivityCertificate
        {
            get { return fActivityCertificate; }
            set { SetPropertyValue<FileData>(nameof(ActivityCertificate), ref fActivityCertificate, value); }
        }
        string fActivityCertificateCode;
        public string ActivityCertificateCode
        {
            get { return fActivityCertificateCode; }
            set { SetPropertyValue<string>(nameof(ActivityCertificateCode), ref fActivityCertificateCode, value); }
        }
        DateTime fActivityCertificateDate;
        public DateTime ActivityCertificateDate
        {
            get { return fActivityCertificateDate; }
            set { SetPropertyValue<DateTime>(nameof(ActivityCertificateDate), ref fActivityCertificateDate, value); }
        }
        string fTaxOffice;
        public string TaxOffice
        {
            get { return fTaxOffice; }
            set { SetPropertyValue<string>(nameof(TaxOffice), ref fTaxOffice, value); }
        }
        string fTaxNumber;
        public string TaxNumber
        {
            get { return fTaxNumber; }
            set { SetPropertyValue<string>(nameof(TaxNumber), ref fTaxNumber, value); }
        }
        Employee fConsultant;
        [Association(@"CustomerReferencesEmployee")]
        public Employee Consultant
        {
            get { return fConsultant; }
            set { SetPropertyValue<Employee>(nameof(Consultant), ref fConsultant, value); }
        }
        Sector fSector;
        [Association(@"CustomerReferencesSector")]
        public Sector Sector
        {
            get { return fSector; }
            set { SetPropertyValue<Sector>(nameof(Sector), ref fSector, value); }
        }
        bool fIsOnlineTransaction;
        public bool IsOnlineTransaction
        {
            get { return fIsOnlineTransaction; }
            set { SetPropertyValue<bool>(nameof(IsOnlineTransaction), ref fIsOnlineTransaction, value); }
        }
        string fUETDSUsername;
        public string UETDSUsername
        {
            get { return fUETDSUsername; }
            set { SetPropertyValue<string>(nameof(UETDSUsername), ref fUETDSUsername, value); }
        }
        string fUETDSPassword;
        public string UETDSPassword
        {
            get { return fUETDSPassword; }
            set { SetPropertyValue<string>(nameof(UETDSPassword), ref fUETDSPassword, value); }
        }
        [Association(@"ActivityReferencesCustomer")]
        public XPCollection<Activity> Activities { get { return GetCollection<Activity>(nameof(Activities)); } }
        [Association(@"ActivityReportReferencesCustomer")]
        public XPCollection<ActivityReport> ActivityReports { get { return GetCollection<ActivityReport>(nameof(ActivityReports)); } }
        [Association(@"AnnualWorkPlanReferencesCustomer")]
        public XPCollection<AnnualWorkPlan> AnnualWorkPlans { get { return GetCollection<AnnualWorkPlan>(nameof(AnnualWorkPlans)); } }
        [Association(@"AuditDeterminationFormReferencesCustomer")]
        public XPCollection<AuditDeterminationForm> AuditDeterminationForms { get { return GetCollection<AuditDeterminationForm>(nameof(AuditDeterminationForms)); } }
        [Association(@"ConsigneeReferencesCustomer")]
        public XPCollection<Consignee> Consignees { get { return GetCollection<Consignee>(nameof(Consignees)); } }
        [Association(@"ContractReferencesCustomer")]
        public XPCollection<Contract> Contracts { get { return GetCollection<Contract>(nameof(Contracts)); } }
        [Association(@"CustomerContactReferencesCustomer")]
        public XPCollection<CustomerContact> CustomerContacts { get { return GetCollection<CustomerContact>(nameof(CustomerContacts)); } }
        [Association(@"CustomerDocumentReferencesCustomer")]
        public XPCollection<CustomerDocument> CustomerDocuments { get { return GetCollection<CustomerDocument>(nameof(CustomerDocuments)); } }
        [Association(@"CustomerInventoryReferencesCustomer")]
        public XPCollection<CustomerInventory> CustomerInventories { get { return GetCollection<CustomerInventory>(nameof(CustomerInventories)); } }
        [Association(@"CustomerWasteInventoryReferencesCustomer")]
        public XPCollection<CustomerWasteInventory> CustomerWasteInventories { get { return GetCollection<CustomerWasteInventory>(nameof(CustomerWasteInventories)); } }
        [Association(@"DefaultVehicleControlDocumentTransactionReferencesCustomer")]
        public XPCollection<DefaultVehicleControlDocumentTransaction> DefaultVehicleControlDocumentTransactions { get { return GetCollection<DefaultVehicleControlDocumentTransaction>(nameof(DefaultVehicleControlDocumentTransactions)); } }
        [Association(@"DistributionOfTaskReferencesCustomer")]
        public XPCollection<DistributionOfTask> DistributionOfTasks { get { return GetCollection<DistributionOfTask>(nameof(DistributionOfTasks)); } }
        [Association(@"DrillFormReferencesCustomer")]
        public XPCollection<DrillForm> DrillForms { get { return GetCollection<DrillForm>(nameof(DrillForms)); } }
        [Association(@"EducationReferencesCustomer")]
        public XPCollection<Education> Educations { get { return GetCollection<Education>(nameof(Educations)); } }
        [Association(@"EmployeeReferencesCustomer")]
        public XPCollection<Employee> Employees { get { return GetCollection<Employee>(nameof(Employees)); } }
        [Association(@"HazardousGoodsTransactionReferencesCustomer")]
        public XPCollection<HazardousGoodsTransaction> HazardousGoodsTransactions { get { return GetCollection<HazardousGoodsTransaction>(nameof(HazardousGoodsTransactions)); } }
        [Association(@"ProductReferencesCustomer")]
        public XPCollection<Product> Products { get { return GetCollection<Product>(nameof(Products)); } }
        [Association(@"QuoteReferencesCustomer")]
        public XPCollection<Quote> Quotes { get { return GetCollection<Quote>(nameof(Quotes)); } }
        [Association(@"ReportOnOccurrenceReferencesCustomer")]
        public XPCollection<ReportOnOccurrence> ReportOnOccurrences { get { return GetCollection<ReportOnOccurrence>(nameof(ReportOnOccurrences)); } }
        [Association(@"TransportDocumentReferencesCustomer")]
        public XPCollection<TransportDocument> TransportDocuments { get { return GetCollection<TransportDocument>(nameof(TransportDocuments)); } }
        [Association(@"VehicleReferencesCustomer")]
        public XPCollection<Vehicle> Vehicles { get { return GetCollection<Vehicle>(nameof(Vehicles)); } }
        [Association(@"VehicleControlDocumentReferencesCustomer")]
        public XPCollection<VehicleControlDocument> VehicleControlDocuments { get { return GetCollection<VehicleControlDocument>(nameof(VehicleControlDocuments)); } }
        [Association(@"VehicleControlDocumentEMailListReferencesCustomer")]
        public XPCollection<VehicleControlDocumentEMailList> VehicleControlDocumentEMailLists { get { return GetCollection<VehicleControlDocumentEMailList>(nameof(VehicleControlDocumentEMailLists)); } }
        [Association(@"VehicleDriverReferencesCustomer")]
        public XPCollection<VehicleDriver> VehicleDrivers { get { return GetCollection<VehicleDriver>(nameof(VehicleDrivers)); } }
    }

}
