//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class DashboardData : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fContent;
        [Size(SizeAttribute.Unlimited)]
        public string Content
        {
            get { return fContent; }
            set { SetPropertyValue<string>(nameof(Content), ref fContent, value); }
        }
        string fTitle;
        public string Title
        {
            get { return fTitle; }
            set { SetPropertyValue<string>(nameof(Title), ref fTitle, value); }
        }
        bool fSynchronizeTitle;
        public bool SynchronizeTitle
        {
            get { return fSynchronizeTitle; }
            set { SetPropertyValue<bool>(nameof(SynchronizeTitle), ref fSynchronizeTitle, value); }
        }
    }

}
