//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class DefaultDistributionOfTaskSubjectDesc : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        DefaultDistributionOfTaskSubject fDefaultSubject;
        [Association(@"DefaultDistributionOfTaskSubjectDescReferencesDefaultDistributionOfTaskSubject")]
        public DefaultDistributionOfTaskSubject DefaultSubject
        {
            get { return fDefaultSubject; }
            set { SetPropertyValue<DefaultDistributionOfTaskSubject>(nameof(DefaultSubject), ref fDefaultSubject, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
    }

}
