//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class Department : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        Employee fManager;
        [Association(@"DepartmentReferencesEmployee")]
        public Employee Manager
        {
            get { return fManager; }
            set { SetPropertyValue<Employee>(nameof(Manager), ref fManager, value); }
        }
        bool fIsManager;
        public bool IsManager
        {
            get { return fIsManager; }
            set { SetPropertyValue<bool>(nameof(IsManager), ref fIsManager, value); }
        }
        [Association(@"EmployeeReferencesDepartment")]
        public XPCollection<Employee> Employees { get { return GetCollection<Employee>(nameof(Employees)); } }
        [Association(@"PositionReferencesDepartment")]
        public XPCollection<Position> Positions { get { return GetCollection<Position>(nameof(Positions)); } }
    }

}
