//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class EmployeeDocument : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        Employee fEmployee;
        [Association(@"EmployeeDocumentReferencesEmployee")]
        public Employee Employee
        {
            get { return fEmployee; }
            set { SetPropertyValue<Employee>(nameof(Employee), ref fEmployee, value); }
        }
        FileData fDocument;
        [Association(@"EmployeeDocumentReferencesFileData")]
        public FileData Document
        {
            get { return fDocument; }
            set { SetPropertyValue<FileData>(nameof(Document), ref fDocument, value); }
        }
    }

}
