//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class HazardousGoodsTransaction : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        int fTransactionType;
        public int TransactionType
        {
            get { return fTransactionType; }
            set { SetPropertyValue<int>(nameof(TransactionType), ref fTransactionType, value); }
        }
        Customer fCustomer;
        [Association(@"HazardousGoodsTransactionReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        Consignee fConsignee;
        [Association(@"HazardousGoodsTransactionReferencesConsignee")]
        public Consignee Consignee
        {
            get { return fConsignee; }
            set { SetPropertyValue<Consignee>(nameof(Consignee), ref fConsignee, value); }
        }
        DateTime fTransactionDate;
        public DateTime TransactionDate
        {
            get { return fTransactionDate; }
            set { SetPropertyValue<DateTime>(nameof(TransactionDate), ref fTransactionDate, value); }
        }
        Product fProduct;
        [Association(@"HazardousGoodsTransactionReferencesProduct")]
        public Product Product
        {
            get { return fProduct; }
            set { SetPropertyValue<Product>(nameof(Product), ref fProduct, value); }
        }
        double fQuantity;
        public double Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<double>(nameof(Quantity), ref fQuantity, value); }
        }
        Unitset fUnitset;
        [Association(@"HazardousGoodsTransactionReferencesUnitset")]
        public Unitset Unitset
        {
            get { return fUnitset; }
            set { SetPropertyValue<Unitset>(nameof(Unitset), ref fUnitset, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        Employee fOwner;
        [Association(@"HazardousGoodsTransactionReferencesEmployee")]
        public Employee Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<Employee>(nameof(Owner), ref fOwner, value); }
        }
    }

}
