//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class HazardousGoodsLimitedExceptLimitedExcepted_HazardousGoodsHazardousGoods : XPBaseObject
    {
        HazardousGoods fHazardousGoods;
        [Indexed(@"LimitedExcepted", Name = @"iHazardousGoodsLimitedExcepted_HazardousGoodsLimitedExceptLimitedExcepted_HazardousGoodsHazardousGoods", Unique = true)]
        [Association(@"HazardousGoodsLimitedExceptLimitedExcepted_HazardousGoodsHazardousGoodsReferencesHazardousGoods")]
        public HazardousGoods HazardousGoods
        {
            get { return fHazardousGoods; }
            set { SetPropertyValue<HazardousGoods>(nameof(HazardousGoods), ref fHazardousGoods, value); }
        }
        HazardousGoodsLimitedExcept fLimitedExcepted;
        [Association(@"HazardousGoodsLimitedExceptLimitedExcepted_HazardousGoodsHazardousGoodsReferencesHazardousGoodsLimitedExcept")]
        public HazardousGoodsLimitedExcept LimitedExcepted
        {
            get { return fLimitedExcepted; }
            set { SetPropertyValue<HazardousGoodsLimitedExcept>(nameof(LimitedExcepted), ref fLimitedExcepted, value); }
        }
        Guid fOID;
        [Key(true)]
        public Guid OID
        {
            get { return fOID; }
            set { SetPropertyValue<Guid>(nameof(OID), ref fOID, value); }
        }
    }

}
