//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class HazardousGoodsPortableTankContainerInstructionPortableTankAndBulkContainerInstructions_HazardousGoodsHazardousGoods : XPBaseObject
    {
        HazardousGoods fHazardousGoods;
        [Indexed(@"PortableTankAndBulkContainerInstructions", Name = @"iHazardousGoodsPortableTankAndBulkContainerInstructions_HazardousGoodsPortableTankContainerInstructionPortableTankAndBu_E24B7419", Unique = true)]
        [Association(@"HazardousGoodsPortableTankContainerInstructionPortableTankAndBulkContainerInstructions_HazardousGoodsHazardousGoodsReferencesHazardousGoods")]
        public HazardousGoods HazardousGoods
        {
            get { return fHazardousGoods; }
            set { SetPropertyValue<HazardousGoods>(nameof(HazardousGoods), ref fHazardousGoods, value); }
        }
        HazardousGoodsPortableTankContainerInstruction fPortableTankAndBulkContainerInstructions;
        [Association(@"HazardousGoodsPortableTankContainerInstructionPortableTankAndBulkContainerInstructions_HazardousGoodsHazardousGoodsReferencesHazardousGoodsPortableTankContainerInstruction")]
        public HazardousGoodsPortableTankContainerInstruction PortableTankAndBulkContainerInstructions
        {
            get { return fPortableTankAndBulkContainerInstructions; }
            set { SetPropertyValue<HazardousGoodsPortableTankContainerInstruction>(nameof(PortableTankAndBulkContainerInstructions), ref fPortableTankAndBulkContainerInstructions, value); }
        }
        Guid fOID;
        [Key(true)]
        public Guid OID
        {
            get { return fOID; }
            set { SetPropertyValue<Guid>(nameof(OID), ref fOID, value); }
        }
    }

}
