//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class HazardousGoodsLabelMixedLoading : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        HazardousGoodsLabel fHazardousGoodsLabel;
        [Association(@"HazardousGoodsLabelMixedLoadingReferencesHazardousGoodsLabel")]
        public HazardousGoodsLabel HazardousGoodsLabel
        {
            get { return fHazardousGoodsLabel; }
            set { SetPropertyValue<HazardousGoodsLabel>(nameof(HazardousGoodsLabel), ref fHazardousGoodsLabel, value); }
        }
        HazardousGoodsLabel fLoadedHazardousGoodsLabel;
        [Association(@"HazardousGoodsLabelMixedLoadingReferencesHazardousGoodsLabel1")]
        public HazardousGoodsLabel LoadedHazardousGoodsLabel
        {
            get { return fLoadedHazardousGoodsLabel; }
            set { SetPropertyValue<HazardousGoodsLabel>(nameof(LoadedHazardousGoodsLabel), ref fLoadedHazardousGoodsLabel, value); }
        }
        int fMixedLoadingType;
        public int MixedLoadingType
        {
            get { return fMixedLoadingType; }
            set { SetPropertyValue<int>(nameof(MixedLoadingType), ref fMixedLoadingType, value); }
        }
    }

}
