//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class HazardousGoodsLabelLabels_HazardousGoodsHazardousGoods : XPBaseObject
    {
        HazardousGoods fHazardousGoods;
        [Indexed(@"Labels", Name = @"iHazardousGoodsLabels_HazardousGoodsLabelLabels_HazardousGoodsHazardousGoods", Unique = true)]
        [Association(@"HazardousGoodsLabelLabels_HazardousGoodsHazardousGoodsReferencesHazardousGoods")]
        public HazardousGoods HazardousGoods
        {
            get { return fHazardousGoods; }
            set { SetPropertyValue<HazardousGoods>(nameof(HazardousGoods), ref fHazardousGoods, value); }
        }
        HazardousGoodsLabel fLabels;
        [Association(@"HazardousGoodsLabelLabels_HazardousGoodsHazardousGoodsReferencesHazardousGoodsLabel")]
        public HazardousGoodsLabel Labels
        {
            get { return fLabels; }
            set { SetPropertyValue<HazardousGoodsLabel>(nameof(Labels), ref fLabels, value); }
        }
        Guid fOID;
        [Key(true)]
        public Guid OID
        {
            get { return fOID; }
            set { SetPropertyValue<Guid>(nameof(OID), ref fOID, value); }
        }
    }

}
