//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class ProductCASNumber : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        Product fProduct;
        [Association(@"ProductCASNumberReferencesProduct")]
        public Product Product
        {
            get { return fProduct; }
            set { SetPropertyValue<Product>(nameof(Product), ref fProduct, value); }
        }
        CASNumber fCASNumber;
        [Association(@"ProductCASNumberReferencesCASNumber")]
        public CASNumber CASNumber
        {
            get { return fCASNumber; }
            set { SetPropertyValue<CASNumber>(nameof(CASNumber), ref fCASNumber, value); }
        }
        double fContentRate;
        public double ContentRate
        {
            get { return fContentRate; }
            set { SetPropertyValue<double>(nameof(ContentRate), ref fContentRate, value); }
        }
        int fCASType;
        public int CASType
        {
            get { return fCASType; }
            set { SetPropertyValue<int>(nameof(CASType), ref fCASType, value); }
        }
    }

}
