//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class Product : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        byte[] fImage;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Image
        {
            get { return fImage; }
            set { SetPropertyValue<byte[]>(nameof(Image), ref fImage, value); }
        }
        int fProductGroupType;
        public int ProductGroupType
        {
            get { return fProductGroupType; }
            set { SetPropertyValue<int>(nameof(ProductGroupType), ref fProductGroupType, value); }
        }
        int fProductType;
        public int ProductType
        {
            get { return fProductType; }
            set { SetPropertyValue<int>(nameof(ProductType), ref fProductType, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fOtherName;
        public string OtherName
        {
            get { return fOtherName; }
            set { SetPropertyValue<string>(nameof(OtherName), ref fOtherName, value); }
        }
        HazardousGoods fHazardousGoods;
        [Association(@"ProductReferencesHazardousGoods")]
        public HazardousGoods HazardousGoods
        {
            get { return fHazardousGoods; }
            set { SetPropertyValue<HazardousGoods>(nameof(HazardousGoods), ref fHazardousGoods, value); }
        }
        Unitset fUnitset;
        [Association(@"ProductReferencesUnitset")]
        public Unitset Unitset
        {
            get { return fUnitset; }
            set { SetPropertyValue<Unitset>(nameof(Unitset), ref fUnitset, value); }
        }
        PackagingTypes fPackagingTypes;
        [Association(@"ProductReferencesPackagingTypes")]
        public PackagingTypes PackagingTypes
        {
            get { return fPackagingTypes; }
            set { SetPropertyValue<PackagingTypes>(nameof(PackagingTypes), ref fPackagingTypes, value); }
        }
        FactoryDepartment fFactoryDepartment;
        [Association(@"ProductReferencesFactoryDepartment")]
        public FactoryDepartment FactoryDepartment
        {
            get { return fFactoryDepartment; }
            set { SetPropertyValue<FactoryDepartment>(nameof(FactoryDepartment), ref fFactoryDepartment, value); }
        }
        FileData fFileData;
        [Association(@"ProductReferencesFileData")]
        public FileData FileData
        {
            get { return fFileData; }
            set { SetPropertyValue<FileData>(nameof(FileData), ref fFileData, value); }
        }
        int fMSDSStatus;
        public int MSDSStatus
        {
            get { return fMSDSStatus; }
            set { SetPropertyValue<int>(nameof(MSDSStatus), ref fMSDSStatus, value); }
        }
        string fMSDSName;
        public string MSDSName
        {
            get { return fMSDSName; }
            set { SetPropertyValue<string>(nameof(MSDSName), ref fMSDSName, value); }
        }
        Customer fCustomer;
        [Association(@"ProductReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        WasteList fWasteCode;
        [Association(@"ProductReferencesWasteList")]
        public WasteList WasteCode
        {
            get { return fWasteCode; }
            set { SetPropertyValue<WasteList>(nameof(WasteCode), ref fWasteCode, value); }
        }
        string fWasteName;
        public string WasteName
        {
            get { return fWasteName; }
            set { SetPropertyValue<string>(nameof(WasteName), ref fWasteName, value); }
        }
        WastePhysicalState fWastePhysicalState;
        [Association(@"ProductReferencesWastePhysicalState")]
        public WastePhysicalState WastePhysicalState
        {
            get { return fWastePhysicalState; }
            set { SetPropertyValue<WastePhysicalState>(nameof(WastePhysicalState), ref fWastePhysicalState, value); }
        }
        bool fIsActive;
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        Employee fOwner;
        [Association(@"ProductReferencesEmployee")]
        public Employee Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<Employee>(nameof(Owner), ref fOwner, value); }
        }
        DateTime fMSDSDateOfValidity;
        public DateTime MSDSDateOfValidity
        {
            get { return fMSDSDateOfValidity; }
            set { SetPropertyValue<DateTime>(nameof(MSDSDateOfValidity), ref fMSDSDateOfValidity, value); }
        }
        [Association(@"HazardousGoodsTransactionReferencesProduct")]
        public XPCollection<HazardousGoodsTransaction> HazardousGoodsTransactions { get { return GetCollection<HazardousGoodsTransaction>(nameof(HazardousGoodsTransactions)); } }
        [Association(@"ProductCASNumberReferencesProduct")]
        public XPCollection<ProductCASNumber> ProductCASNumbers { get { return GetCollection<ProductCASNumber>(nameof(ProductCASNumbers)); } }
        [Association(@"ProductLabelReferencesProduct")]
        public XPCollection<ProductLabel> ProductLabels { get { return GetCollection<ProductLabel>(nameof(ProductLabels)); } }
        [Association(@"ProductSupplierReferencesProduct")]
        public XPCollection<ProductSupplier> ProductSuppliers { get { return GetCollection<ProductSupplier>(nameof(ProductSuppliers)); } }
    }

}
