//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class Quote : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        Employee fOwner;
        [Association(@"QuoteReferencesEmployee")]
        public Employee Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<Employee>(nameof(Owner), ref fOwner, value); }
        }
        int fCustomerType;
        public int CustomerType
        {
            get { return fCustomerType; }
            set { SetPropertyValue<int>(nameof(CustomerType), ref fCustomerType, value); }
        }
        Customer fCustomer;
        [Association(@"QuoteReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        Lead fLead;
        [Association(@"QuoteReferencesLead")]
        public Lead Lead
        {
            get { return fLead; }
            set { SetPropertyValue<Lead>(nameof(Lead), ref fLead, value); }
        }
        string fAddress;
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        string fTelephone;
        public string Telephone
        {
            get { return fTelephone; }
            set { SetPropertyValue<string>(nameof(Telephone), ref fTelephone, value); }
        }
        string fEMail;
        public string EMail
        {
            get { return fEMail; }
            set { SetPropertyValue<string>(nameof(EMail), ref fEMail, value); }
        }
        string fContact;
        public string Contact
        {
            get { return fContact; }
            set { SetPropertyValue<string>(nameof(Contact), ref fContact, value); }
        }
        DateTime fDateOfValidity;
        public DateTime DateOfValidity
        {
            get { return fDateOfValidity; }
            set { SetPropertyValue<DateTime>(nameof(DateOfValidity), ref fDateOfValidity, value); }
        }
        int fServiceDay;
        public int ServiceDay
        {
            get { return fServiceDay; }
            set { SetPropertyValue<int>(nameof(ServiceDay), ref fServiceDay, value); }
        }
        double fActivityCertificatePrice;
        public double ActivityCertificatePrice
        {
            get { return fActivityCertificatePrice; }
            set { SetPropertyValue<double>(nameof(ActivityCertificatePrice), ref fActivityCertificatePrice, value); }
        }
        double fEducationPrice;
        public double EducationPrice
        {
            get { return fEducationPrice; }
            set { SetPropertyValue<double>(nameof(EducationPrice), ref fEducationPrice, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
    }

}
