//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class TransportDocumentOtherTransaction : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        TransportDocument fTransportDocument;
        [Association(@"TransportDocumentOtherTransactionReferencesTransportDocument")]
        public TransportDocument TransportDocument
        {
            get { return fTransportDocument; }
            set { SetPropertyValue<TransportDocument>(nameof(TransportDocument), ref fTransportDocument, value); }
        }
        HazardousGoods fHazardousGoods;
        [Association(@"TransportDocumentOtherTransactionReferencesHazardousGoods")]
        public HazardousGoods HazardousGoods
        {
            get { return fHazardousGoods; }
            set { SetPropertyValue<HazardousGoods>(nameof(HazardousGoods), ref fHazardousGoods, value); }
        }
        HazardousGoodsClass fHazardousGoodsClass;
        [Association(@"TransportDocumentOtherTransactionReferencesHazardousGoodsClass")]
        public HazardousGoodsClass HazardousGoodsClass
        {
            get { return fHazardousGoodsClass; }
            set { SetPropertyValue<HazardousGoodsClass>(nameof(HazardousGoodsClass), ref fHazardousGoodsClass, value); }
        }
        PackingGroup fPackingGroup;
        [Association(@"TransportDocumentOtherTransactionReferencesPackingGroup")]
        public PackingGroup PackingGroup
        {
            get { return fPackingGroup; }
            set { SetPropertyValue<PackingGroup>(nameof(PackingGroup), ref fPackingGroup, value); }
        }
        double fQuantity;
        public double Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<double>(nameof(Quantity), ref fQuantity, value); }
        }
        PackagingTypes fPackagingTypes;
        [Association(@"TransportDocumentOtherTransactionReferencesPackagingTypes")]
        public PackagingTypes PackagingTypes
        {
            get { return fPackagingTypes; }
            set { SetPropertyValue<PackagingTypes>(nameof(PackagingTypes), ref fPackagingTypes, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        double fNetWeigth;
        public double NetWeigth
        {
            get { return fNetWeigth; }
            set { SetPropertyValue<double>(nameof(NetWeigth), ref fNetWeigth, value); }
        }
        WasteList fWasteCode;
        [Association(@"TransportDocumentOtherTransactionReferencesWasteList")]
        public WasteList WasteCode
        {
            get { return fWasteCode; }
            set { SetPropertyValue<WasteList>(nameof(WasteCode), ref fWasteCode, value); }
        }
        HazardousGoodsLabel fHazardousGoodsLabel;
        [Association(@"TransportDocumentOtherTransactionReferencesHazardousGoodsLabel")]
        public HazardousGoodsLabel HazardousGoodsLabel
        {
            get { return fHazardousGoodsLabel; }
            set { SetPropertyValue<HazardousGoodsLabel>(nameof(HazardousGoodsLabel), ref fHazardousGoodsLabel, value); }
        }
        Unitset fUnitset;
        [Association(@"TransportDocumentOtherTransactionReferencesUnitset")]
        public Unitset Unitset
        {
            get { return fUnitset; }
            set { SetPropertyValue<Unitset>(nameof(Unitset), ref fUnitset, value); }
        }
        int fVal;
        public int Val
        {
            get { return fVal; }
            set { SetPropertyValue<int>(nameof(Val), ref fVal, value); }
        }
        HazardousGoodsTunnelCode fTunnelCode;
        [Association(@"TransportDocumentOtherTransactionReferencesHazardousGoodsTunnelCode")]
        public HazardousGoodsTunnelCode TunnelCode
        {
            get { return fTunnelCode; }
            set { SetPropertyValue<HazardousGoodsTunnelCode>(nameof(TunnelCode), ref fTunnelCode, value); }
        }
        int fConvFactor;
        public int ConvFactor
        {
            get { return fConvFactor; }
            set { SetPropertyValue<int>(nameof(ConvFactor), ref fConvFactor, value); }
        }
        double fTotalConvFactor;
        public double TotalConvFactor
        {
            get { return fTotalConvFactor; }
            set { SetPropertyValue<double>(nameof(TotalConvFactor), ref fTotalConvFactor, value); }
        }
        HazardousGoodsTransportCategory fTransportCategory;
        [Association(@"TransportDocumentOtherTransactionReferencesHazardousGoodsTransportCategory")]
        public HazardousGoodsTransportCategory TransportCategory
        {
            get { return fTransportCategory; }
            set { SetPropertyValue<HazardousGoodsTransportCategory>(nameof(TransportCategory), ref fTransportCategory, value); }
        }
        [Association(@"VoyageNotificationTransactionReferencesTransportDocumentOtherTransaction")]
        public XPCollection<VoyageNotificationTransaction> VoyageNotificationTransactions { get { return GetCollection<VoyageNotificationTransaction>(nameof(VoyageNotificationTransactions)); } }
    }

}
