//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class Unitset : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        [Association(@"ActivityReportTransactionReferencesUnitset")]
        public XPCollection<ActivityReportTransaction> ActivityReportTransactions { get { return GetCollection<ActivityReportTransaction>(nameof(ActivityReportTransactions)); } }
        [Association(@"CustomerInventoryReferencesUnitset")]
        public XPCollection<CustomerInventory> CustomerInventories { get { return GetCollection<CustomerInventory>(nameof(CustomerInventories)); } }
        [Association(@"CustomerInventoryReferencesUnitset1")]
        public XPCollection<CustomerInventory> CustomerInventories1 { get { return GetCollection<CustomerInventory>(nameof(CustomerInventories1)); } }
        [Association(@"HazardousGoodsTransactionReferencesUnitset")]
        public XPCollection<HazardousGoodsTransaction> HazardousGoodsTransactions { get { return GetCollection<HazardousGoodsTransaction>(nameof(HazardousGoodsTransactions)); } }
        [Association(@"ProductReferencesUnitset")]
        public XPCollection<Product> Products { get { return GetCollection<Product>(nameof(Products)); } }
        [Association(@"TransportDocumentOtherTransactionReferencesUnitset")]
        public XPCollection<TransportDocumentOtherTransaction> TransportDocumentOtherTransactions { get { return GetCollection<TransportDocumentOtherTransaction>(nameof(TransportDocumentOtherTransactions)); } }
        [Association(@"TransportDocumentTransactionReferencesUnitset")]
        public XPCollection<TransportDocumentTransaction> TransportDocumentTransactions { get { return GetCollection<TransportDocumentTransaction>(nameof(TransportDocumentTransactions)); } }
    }

}
