//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class VehicleControlDocumentTransaction : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        VehicleControlDocument fVehicleControlDocument;
        [Association(@"VehicleControlDocumentTransactionReferencesVehicleControlDocument")]
        public VehicleControlDocument VehicleControlDocument
        {
            get { return fVehicleControlDocument; }
            set { SetPropertyValue<VehicleControlDocument>(nameof(VehicleControlDocument), ref fVehicleControlDocument, value); }
        }
        string fQuestion;
        public string Question
        {
            get { return fQuestion; }
            set { SetPropertyValue<string>(nameof(Question), ref fQuestion, value); }
        }
        bool fAnswer;
        public bool Answer
        {
            get { return fAnswer; }
            set { SetPropertyValue<bool>(nameof(Answer), ref fAnswer, value); }
        }
        string fHint;
        public string Hint
        {
            get { return fHint; }
            set { SetPropertyValue<string>(nameof(Hint), ref fHint, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        HazardousGoodsLabel fHazardousGoodsLabel;
        [Association(@"VehicleControlDocumentTransactionReferencesHazardousGoodsLabel")]
        public HazardousGoodsLabel HazardousGoodsLabel
        {
            get { return fHazardousGoodsLabel; }
            set { SetPropertyValue<HazardousGoodsLabel>(nameof(HazardousGoodsLabel), ref fHazardousGoodsLabel, value); }
        }
    }

}
