//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class VehicleDriver : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fFirstName;
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
        }
        string fLastName;
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>(nameof(LastName), ref fLastName, value); }
        }
        Customer fCustomer;
        [Association(@"VehicleDriverReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        DateTime fSRCDateOfValidity;
        public DateTime SRCDateOfValidity
        {
            get { return fSRCDateOfValidity; }
            set { SetPropertyValue<DateTime>(nameof(SRCDateOfValidity), ref fSRCDateOfValidity, value); }
        }
        string fSRC5DocumentNo;
        public string SRC5DocumentNo
        {
            get { return fSRC5DocumentNo; }
            set { SetPropertyValue<string>(nameof(SRC5DocumentNo), ref fSRC5DocumentNo, value); }
        }
        DateTime fPsychotechnicalExamination;
        public DateTime PsychotechnicalExamination
        {
            get { return fPsychotechnicalExamination; }
            set { SetPropertyValue<DateTime>(nameof(PsychotechnicalExamination), ref fPsychotechnicalExamination, value); }
        }
        string fTCKN;
        public string TCKN
        {
            get { return fTCKN; }
            set { SetPropertyValue<string>(nameof(TCKN), ref fTCKN, value); }
        }
        [Association(@"TransportDocumentReferencesVehicleDriver")]
        public XPCollection<TransportDocument> TransportDocuments { get { return GetCollection<TransportDocument>(nameof(TransportDocuments)); } }
        [Association(@"VehicleControlDocumentReferencesVehicleDriver")]
        public XPCollection<VehicleControlDocument> VehicleControlDocuments { get { return GetCollection<VehicleControlDocument>(nameof(VehicleControlDocuments)); } }
        [Association(@"VehicleDriverCompetenceCertificateReferencesVehicleDriver")]
        public XPCollection<VehicleDriverCompetenceCertificate> VehicleDriverCompetenceCertificates { get { return GetCollection<VehicleDriverCompetenceCertificate>(nameof(VehicleDriverCompetenceCertificates)); } }
        [Association(@"VehicleDriverDocumentReferencesVehicleDriver")]
        public XPCollection<VehicleDriverDocument> VehicleDriverDocuments { get { return GetCollection<VehicleDriverDocument>(nameof(VehicleDriverDocuments)); } }
    }

}
