//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class VehicleControlDocumentHazardousGoods : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        VehicleControlDocument fVehicleControlDocument;
        [Association(@"VehicleControlDocumentHazardousGoodsReferencesVehicleControlDocument")]
        public VehicleControlDocument VehicleControlDocument
        {
            get { return fVehicleControlDocument; }
            set { SetPropertyValue<VehicleControlDocument>(nameof(VehicleControlDocument), ref fVehicleControlDocument, value); }
        }
        HazardousGoods fHazardousGoods;
        [Association(@"VehicleControlDocumentHazardousGoodsReferencesHazardousGoods")]
        public HazardousGoods HazardousGoods
        {
            get { return fHazardousGoods; }
            set { SetPropertyValue<HazardousGoods>(nameof(HazardousGoods), ref fHazardousGoods, value); }
        }
    }

}
