//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class VehicleDriverDocument : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        VehicleDriver fVehicleDriver;
        [Association(@"VehicleDriverDocumentReferencesVehicleDriver")]
        public VehicleDriver VehicleDriver
        {
            get { return fVehicleDriver; }
            set { SetPropertyValue<VehicleDriver>(nameof(VehicleDriver), ref fVehicleDriver, value); }
        }
        FileData fFileData;
        [Association(@"VehicleDriverDocumentReferencesFileData")]
        public FileData FileData
        {
            get { return fFileData; }
            set { SetPropertyValue<FileData>(nameof(FileData), ref fFileData, value); }
        }
        Employee fOwner;
        [Association(@"VehicleDriverDocumentReferencesEmployee")]
        public Employee Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<Employee>(nameof(Owner), ref fOwner, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
    }

}
