//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class VoyageNotification : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        long fReferenceId;
        public long ReferenceId
        {
            get { return fReferenceId; }
            set { SetPropertyValue<long>(nameof(ReferenceId), ref fReferenceId, value); }
        }
        TransportDocument fTransportDocument;
        [Association(@"VoyageNotificationReferencesTransportDocument")]
        public TransportDocument TransportDocument
        {
            get { return fTransportDocument; }
            set { SetPropertyValue<TransportDocument>(nameof(TransportDocument), ref fTransportDocument, value); }
        }
        DateTime fUpdatedDate;
        public DateTime UpdatedDate
        {
            get { return fUpdatedDate; }
            set { SetPropertyValue<DateTime>(nameof(UpdatedDate), ref fUpdatedDate, value); }
        }
        DateTime fActivatedDate;
        public DateTime ActivatedDate
        {
            get { return fActivatedDate; }
            set { SetPropertyValue<DateTime>(nameof(ActivatedDate), ref fActivatedDate, value); }
        }
        int fStatus;
        public int Status
        {
            get { return fStatus; }
            set { SetPropertyValue<int>(nameof(Status), ref fStatus, value); }
        }
        DateTime fStartDate;
        public DateTime StartDate
        {
            get { return fStartDate; }
            set { SetPropertyValue<DateTime>(nameof(StartDate), ref fStartDate, value); }
        }
        double fStartTime;
        public double StartTime
        {
            get { return fStartTime; }
            set { SetPropertyValue<double>(nameof(StartTime), ref fStartTime, value); }
        }
        DateTime fEndDate;
        public DateTime EndDate
        {
            get { return fEndDate; }
            set { SetPropertyValue<DateTime>(nameof(EndDate), ref fEndDate, value); }
        }
        double fEndTime;
        public double EndTime
        {
            get { return fEndTime; }
            set { SetPropertyValue<double>(nameof(EndTime), ref fEndTime, value); }
        }
        string fFirmVoyageNumber;
        public string FirmVoyageNumber
        {
            get { return fFirmVoyageNumber; }
            set { SetPropertyValue<string>(nameof(FirmVoyageNumber), ref fFirmVoyageNumber, value); }
        }
        string fPlate1;
        public string Plate1
        {
            get { return fPlate1; }
            set { SetPropertyValue<string>(nameof(Plate1), ref fPlate1, value); }
        }
        string fPlate2;
        public string Plate2
        {
            get { return fPlate2; }
            set { SetPropertyValue<string>(nameof(Plate2), ref fPlate2, value); }
        }
        string fDriver1TCKN;
        public string Driver1TCKN
        {
            get { return fDriver1TCKN; }
            set { SetPropertyValue<string>(nameof(Driver1TCKN), ref fDriver1TCKN, value); }
        }
        string fDriver2TCKN;
        public string Driver2TCKN
        {
            get { return fDriver2TCKN; }
            set { SetPropertyValue<string>(nameof(Driver2TCKN), ref fDriver2TCKN, value); }
        }
        int fCancelledType;
        public int CancelledType
        {
            get { return fCancelledType; }
            set { SetPropertyValue<int>(nameof(CancelledType), ref fCancelledType, value); }
        }
        string fCancelledDescription;
        public string CancelledDescription
        {
            get { return fCancelledDescription; }
            set { SetPropertyValue<string>(nameof(CancelledDescription), ref fCancelledDescription, value); }
        }
        DateTime fCancelledDate;
        public DateTime CancelledDate
        {
            get { return fCancelledDate; }
            set { SetPropertyValue<DateTime>(nameof(CancelledDate), ref fCancelledDate, value); }
        }
        Employee fOwner;
        [Association(@"VoyageNotificationReferencesEmployee")]
        public Employee Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<Employee>(nameof(Owner), ref fOwner, value); }
        }
        [Association(@"VoyageNotificationHistoryReferencesVoyageNotification")]
        public XPCollection<VoyageNotificationHistory> VoyageNotificationHistories { get { return GetCollection<VoyageNotificationHistory>(nameof(VoyageNotificationHistories)); } }
        [Association(@"VoyageNotificationTransactionReferencesVoyageNotification")]
        public XPCollection<VoyageNotificationTransaction> VoyageNotificationTransactions { get { return GetCollection<VoyageNotificationTransaction>(nameof(VoyageNotificationTransactions)); } }
    }

}
