//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace iyibir.TMGD.WebAPI.OData.Models.iyibir_TMGD
{

    public partial class VoyageNotificationTransaction : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        long fReferenceId;
        public long ReferenceId
        {
            get { return fReferenceId; }
            set { SetPropertyValue<long>(nameof(ReferenceId), ref fReferenceId, value); }
        }
        TransportDocumentOtherTransaction fOtherTransaction;
        [Association(@"VoyageNotificationTransactionReferencesTransportDocumentOtherTransaction")]
        public TransportDocumentOtherTransaction OtherTransaction
        {
            get { return fOtherTransaction; }
            set { SetPropertyValue<TransportDocumentOtherTransaction>(nameof(OtherTransaction), ref fOtherTransaction, value); }
        }
        TransportDocumentTransaction fTransaction;
        [Association(@"VoyageNotificationTransactionReferencesTransportDocumentTransaction")]
        public TransportDocumentTransaction Transaction
        {
            get { return fTransaction; }
            set { SetPropertyValue<TransportDocumentTransaction>(nameof(Transaction), ref fTransaction, value); }
        }
        int fStatus;
        public int Status
        {
            get { return fStatus; }
            set { SetPropertyValue<int>(nameof(Status), ref fStatus, value); }
        }
        VoyageNotification fVoyageNotification;
        [Association(@"VoyageNotificationTransactionReferencesVoyageNotification")]
        public VoyageNotification VoyageNotification
        {
            get { return fVoyageNotification; }
            set { SetPropertyValue<VoyageNotification>(nameof(VoyageNotification), ref fVoyageNotification, value); }
        }
        int fTransportTypeCode;
        public int TransportTypeCode
        {
            get { return fTransportTypeCode; }
            set { SetPropertyValue<int>(nameof(TransportTypeCode), ref fTransportTypeCode, value); }
        }
        string fConsignerVKN;
        public string ConsignerVKN
        {
            get { return fConsignerVKN; }
            set { SetPropertyValue<string>(nameof(ConsignerVKN), ref fConsignerVKN, value); }
        }
        string fConsignerTitle;
        public string ConsignerTitle
        {
            get { return fConsignerTitle; }
            set { SetPropertyValue<string>(nameof(ConsignerTitle), ref fConsignerTitle, value); }
        }
        string fConsigneeVKN;
        public string ConsigneeVKN
        {
            get { return fConsigneeVKN; }
            set { SetPropertyValue<string>(nameof(ConsigneeVKN), ref fConsigneeVKN, value); }
        }
        string fConsigneeTitle;
        public string ConsigneeTitle
        {
            get { return fConsigneeTitle; }
            set { SetPropertyValue<string>(nameof(ConsigneeTitle), ref fConsigneeTitle, value); }
        }
        string fConsignerCountryCode;
        public string ConsignerCountryCode
        {
            get { return fConsignerCountryCode; }
            set { SetPropertyValue<string>(nameof(ConsignerCountryCode), ref fConsignerCountryCode, value); }
        }
        string fConsignerCityMernisCode;
        public string ConsignerCityMernisCode
        {
            get { return fConsignerCityMernisCode; }
            set { SetPropertyValue<string>(nameof(ConsignerCityMernisCode), ref fConsignerCityMernisCode, value); }
        }
        string fConsignerCountyMernisCode;
        public string ConsignerCountyMernisCode
        {
            get { return fConsignerCountyMernisCode; }
            set { SetPropertyValue<string>(nameof(ConsignerCountyMernisCode), ref fConsignerCountyMernisCode, value); }
        }
        string fConsigneeCountryCode;
        public string ConsigneeCountryCode
        {
            get { return fConsigneeCountryCode; }
            set { SetPropertyValue<string>(nameof(ConsigneeCountryCode), ref fConsigneeCountryCode, value); }
        }
        string fConsigneeCityMernisCode;
        public string ConsigneeCityMernisCode
        {
            get { return fConsigneeCityMernisCode; }
            set { SetPropertyValue<string>(nameof(ConsigneeCityMernisCode), ref fConsigneeCityMernisCode, value); }
        }
        string fConsigneeCountyMernisCode;
        public string ConsigneeCountyMernisCode
        {
            get { return fConsigneeCountyMernisCode; }
            set { SetPropertyValue<string>(nameof(ConsigneeCountyMernisCode), ref fConsigneeCountyMernisCode, value); }
        }
        DateTime fLadingDate;
        public DateTime LadingDate
        {
            get { return fLadingDate; }
            set { SetPropertyValue<DateTime>(nameof(LadingDate), ref fLadingDate, value); }
        }
        double fLadingTime;
        public double LadingTime
        {
            get { return fLadingTime; }
            set { SetPropertyValue<double>(nameof(LadingTime), ref fLadingTime, value); }
        }
        DateTime fPouringDate;
        public DateTime PouringDate
        {
            get { return fPouringDate; }
            set { SetPropertyValue<DateTime>(nameof(PouringDate), ref fPouringDate, value); }
        }
        double fPouringTime;
        public double PouringTime
        {
            get { return fPouringTime; }
            set { SetPropertyValue<double>(nameof(PouringTime), ref fPouringTime, value); }
        }
        LoadType fLoadType;
        [Association(@"VoyageNotificationTransactionReferencesLoadType")]
        public LoadType LoadType
        {
            get { return fLoadType; }
            set { SetPropertyValue<LoadType>(nameof(LoadType), ref fLoadType, value); }
        }
        string fLoadOtherDescription;
        public string LoadOtherDescription
        {
            get { return fLoadOtherDescription; }
            set { SetPropertyValue<string>(nameof(LoadOtherDescription), ref fLoadOtherDescription, value); }
        }
        int fHazardousUnit;
        public int HazardousUnit
        {
            get { return fHazardousUnit; }
            set { SetPropertyValue<int>(nameof(HazardousUnit), ref fHazardousUnit, value); }
        }
        int fOtherUnit;
        public int OtherUnit
        {
            get { return fOtherUnit; }
            set { SetPropertyValue<int>(nameof(OtherUnit), ref fOtherUnit, value); }
        }
        double fLoadQuantity;
        public double LoadQuantity
        {
            get { return fLoadQuantity; }
            set { SetPropertyValue<double>(nameof(LoadQuantity), ref fLoadQuantity, value); }
        }
        string fFirmLoadNumber;
        public string FirmLoadNumber
        {
            get { return fFirmLoadNumber; }
            set { SetPropertyValue<string>(nameof(FirmLoadNumber), ref fFirmLoadNumber, value); }
        }
        int fHazardousTransportType;
        public int HazardousTransportType
        {
            get { return fHazardousTransportType; }
            set { SetPropertyValue<int>(nameof(HazardousTransportType), ref fHazardousTransportType, value); }
        }
        string fUnId;
        public string UnId
        {
            get { return fUnId; }
            set { SetPropertyValue<string>(nameof(UnId), ref fUnId, value); }
        }
        int fHazardousExemptionType;
        public int HazardousExemptionType
        {
            get { return fHazardousExemptionType; }
            set { SetPropertyValue<int>(nameof(HazardousExemptionType), ref fHazardousExemptionType, value); }
        }
        int fCancelledType;
        public int CancelledType
        {
            get { return fCancelledType; }
            set { SetPropertyValue<int>(nameof(CancelledType), ref fCancelledType, value); }
        }
        string fCancelledDescription;
        public string CancelledDescription
        {
            get { return fCancelledDescription; }
            set { SetPropertyValue<string>(nameof(CancelledDescription), ref fCancelledDescription, value); }
        }
        DateTime fCancelledDate;
        public DateTime CancelledDate
        {
            get { return fCancelledDate; }
            set { SetPropertyValue<DateTime>(nameof(CancelledDate), ref fCancelledDate, value); }
        }
        DateTime fActivatedDate;
        public DateTime ActivatedDate
        {
            get { return fActivatedDate; }
            set { SetPropertyValue<DateTime>(nameof(ActivatedDate), ref fActivatedDate, value); }
        }
        DateTime fUpdatedDate;
        public DateTime UpdatedDate
        {
            get { return fUpdatedDate; }
            set { SetPropertyValue<DateTime>(nameof(UpdatedDate), ref fUpdatedDate, value); }
        }
        int fLineNumber;
        public int LineNumber
        {
            get { return fLineNumber; }
            set { SetPropertyValue<int>(nameof(LineNumber), ref fLineNumber, value); }
        }
    }

}
